### ISSUE TITLE
Failed profile collection in uptime perf test

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/mobile-testkit#1012]
In the 72h uptime performance test, go profile collection ended about 1/3 of the way into the run.

The test ran from 19:42 March 2 to 19:42 March 5, but the collected profiles are only included from 19:51 March 2 - 19:15 on March 3.

http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/
http://s61103cnt72.sc.couchbase.com:3000/dashboard/db/sync-gateway-perf-test?var-perftestrundbs=jenkins-sync-gateway-perf-test-530&from=1488512527098&to=1488771727000

**Comment by sethrosetter** [comment]
Profile collection script - https://github.com/couchbaselabs/mobile-testkit/blob/4a86cf6ed4164e44b664b6b503f4a502922cc84f/libraries/provision/ansible/playbooks/files/sync_gateway_collect_profile.py

**Comment by raghusarangapani** [comment]
start-profile-collection.yml is hard coded to run profile collection for 86400s (24 hours)

```
 # Copy profile collection script to sync_gateways
  - name: copy the profile collection script
    copy: src=files/sync_gateway_collect_profile.py dest=/home/sync_gateway/ owner=sync_gateway group=sync_gateway mode=755
  # Start collecting profile, no polling and a 24 hour timeout
  - name: start profile collection
    shell: ./sync_gateway_collect_profile.py --sg-binary /opt/couchbase-sync-gateway/bin/sync_gateway --format-type-pdf --format-type-text --profile-type-heap --profile-type-cpu --profile-type-goroutine --heap-alloc-space --heap-inuse-space --delay-secs 540 chdir=/home/sync_gateway/
    async: 86400
    poll: 0
 ```

**Comment by raghusarangapani** [comment]
Fixed through https://github.com/couchbaselabs/mobile-testkit/pull/1036
