### ISSUE TITLE
XATTRs: Matrix testing of CRUD ops with SDK

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1046]
| | SDK Create | SDK Read | SDK Update | SDK Delete |
| - | - | - | - | - |
| Sync Gateway Create | | | | |
| Sync Gateway Read | | | | |
| Sync Gateway Update | | | | |
| Sync Gateway Delete | | | | |

- [ ] Unique docs
- [ ] Conflicting updates

**Comment by sethrosetter** [comment]
We may not have to separate this, we could cover multiple ops in certain tests cases

**Comment by sethrosetter** [comment]
Scenarios:

- [ ] CRUD one side
  - SG Create / Update, start changes
  - SDK Create / Update, start changes
  - SG sees SDK doc creates / updates
  - SDK sees SG doc creates / updates
  - SG deletes docs
  - SDK deletes docs
  - SDK sees SG deletes
  - SG sees SDKdeletes
- [ ]  Shared Updates from both sides
  - SG creates docs (shared)
  - SDK creates docs (shared)
  - SG updates all docs, new_edits=True with retry if conflict
  - SDK updates all docs, new_edits=True?? with retry if conflict
  - SG sees all updates
  - SDK sees all updates
  - SG  / SDK delete all docs
- [ ]  Shared Updates with conflicts from both sides
  - SG creates docs (shared)
  - SDK creates docs (shared)
  - SG updates all docs, new_edits=False (Create conflicts)
  - SDK updates all docs,  new_edits=False ?? (Create conflicts)
  - SG sees all updates
  - SDK sees all updates
  - SG / SDK delete all docs

**Comment by sethrosetter** [comment]
Need to review with @adamcfraser if this is required for GA

**Comment by sethrosetter** [comment]
Maybe best to implement in this scenario or use as a reference to implement a new one.

**Comment by sridevi-15** [comment]
Clarify Unimplemented Scenario with @adamcfraser when starting the implementation

**Comment by sridevi-15** [comment]
SG - rev 1-foo

                  SDK write
                  SG import of SDK write - 2-foo

SG - rev 2-bar, parent 1-foo, new_edits=true
 - gets 409
 - reloads doc, gets 2-foo
 SG updates rev 3-bar, parent 2-foo
  - succeeds


-----
SG - rev 2-bar, parent 1-foo, new_edits=false
- succeed, rev tree looks like:
1 - foo
 |- 2-foo  
 |- 2-bar  (active)
   |- 3-bar

                  SDK write
                  SG import of SDK write, creates 3-bar


Assert that the import of the SDK write is successful
Assert that no errors when doing SG updates
