### ISSUE TITLE
Rename func test jenkins fields to VERSION_OR_COMMIT

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#1047]
Factored out of https://github.com/couchbaselabs/mobile-testkit/issues/1037

**Comment by tleyden** [comment]
@sethrosetter / @raghusarangapani ok I changed all 4 functional test jenkins jobs name the field `SYNC_GATEWAY_VERSION_OR_COMMIT`

Also I changed them to have a flag to stream the pytest output `-s`, which is useful for debugging issues.  Defaults to existing behavior of not including `-s`, so reports work.

**Comment by sethrosetter** [comment]
@tleyden Awesome. This is going to be really useful going forward
