### ISSUE TITLE
XATTRs: On demand processing of docs

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1048]
Sync Gateway to process document mutations in real-time for requests (e.g. via SG Get()) of documents that have not yet been processed

**Comment by sethrosetter** [comment]
These scenarios test on demand processing of docs in real time if they have not yet been processed. 

2 ways of determining if a doc has not yet been processed
- Validate that the on demand expvar shows that this functionality is being excercised. Need expvar exposed on Sync Gateway
- Run against single node with XATTR support and importer disabled

**Comment by sethrosetter** [comment]
Fabricated Scenarios (autoimport disabled)
- [ ] SG Concurrent Reads /  Concurrent external writes
  - Docs are added via SDK in parallel
  - Docs are written to Couchbase Server
  - Perform concurrent GETs to Sync gateway with the correct channels and verify that you can get the appropriated docs
  - Ensure document is only processed once ?.

**Comment by sethrosetter** [comment]
@adamcfraser Should we test other ops besides SG read for these scenarios?

**Comment by sethrosetter** [comment]
Need to include SG Reads and SG writes

**Comment by sethrosetter** [comment]
WIP - https://github.com/couchbaselabs/mobile-testkit/commit/e668bed0543553f0181d4dd4cce89f77463d1d84

**Comment by sridevi-15** [comment]
How do we disable import in Distributed index? @adamcfraser . Is it possible to test ?

**Comment by sridevi-15** [comment]
Check with @adamcfraser, no need to support  distributed index scenario, testing with channel cache is fine.
