### ISSUE TITLE
XATTRs: High revs testing

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1051]
High revs testing (> 1000 revs), make sure no space issues with XATTS, Also can do 'high revs limit + high # access grants + high # channels

**Comment by sethrosetter** [comment]
- [ ] (-) Out of XATTR space handling
  - Set very high revs_limit
  - Create high number of revs until rev trees fills up XATTR space
  - Verify that this situation is handled gracefully

**Comment by sethrosetter** [comment]
Some outstanding questions:
- [ ] How to find current quota of XATTR space
- [ ] How do we ensure we have filled up the XATTR space?

**Comment by sethrosetter** [comment]
To get XATTRS `:4985/db/_raw/doc_name` to verify revision tree size.

**Comment by sethrosetter** [comment]
- [ ] Play around manually
- [ ] Add scenario to test_xattrs.py

**Comment by raghusarangapani** [comment]
I manually tried out the below 2 scenarios:

scenario 1:
- SG 1.5 without xattrs running on a VM.
- VM has 2GB RAM.
- Add one doc to SG.
- revs_limit is set to 10 million.
- Constantly update the doc with a script.
- After about 8000 updates, SG gets killed by the OS.
- When SG gets killed, SG is using around 90% cpu and all the memory and the OS is running out of memory.

/var/log/messages:
```
Jun 14 21:59:16 localhost kernel: 38610 total pagecache pages
Jun 14 21:59:16 localhost kernel: 35800 pages in swap cache
Jun 14 21:59:16 localhost kernel: Swap cache stats: add 16917332, delete 16881532, find 5161984/6611476
Jun 14 21:59:16 localhost kernel: Free swap  = 0kB
Jun 14 21:59:16 localhost kernel: Total swap = 1572860kB
Jun 14 21:59:16 localhost kernel: 524174 pages RAM
Jun 14 21:59:16 localhost kernel: 0 pages HighMem/MovableOnly
Jun 14 21:59:16 localhost kernel: 53130 pages reserved
Jun 14 21:59:16 localhost kernel: [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
Jun 14 21:59:16 localhost kernel: [ 3288]     0  3288   831901   398350    1519   366000             0 sync_gateway
Jun 14 21:40:02 localhost kernel: Out of memory: Kill process 2777 (sync_gateway) score 874 or sacrifice child
Jun 14 21:40:02 localhost kernel: Killed process 2777 (sync_gateway) total-vm:3285600kB, anon-rss:1554664kB, file-rss:0kB
```
scenario 1:
- SG 1.5 with xattrs enabled running on a VM.
- VM has 6GB RAM.
- Add one doc to SG.
- revs_limit is set to 10 million.
- Constantly update the doc with a script.
- After about 16568 updates, SG gets killed by the OS.
- When SG gets killed, SG is using around 90% cpu and all the memory and the OS is running out of memory.

/var/log/messages:
```
Jun 14 22:53:19 localhost kernel: Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
Jun 14 22:53:19 localhost kernel: 62698 total pagecache pages
Jun 14 22:53:19 localhost kernel: 58157 pages in swap cache
Jun 14 22:53:19 localhost kernel: Swap cache stats: add 2824375, delete 2766218, find 763838/1027429
Jun 14 22:53:19 localhost kernel: Free swap  = 0kB
Jun 14 22:53:19 localhost kernel: Total swap = 1572860kB
Jun 14 22:53:19 localhost kernel: 1572750 pages RAM
Jun 14 22:53:19 localhost kernel: 0 pages HighMem/MovableOnly
Jun 14 22:53:19 localhost kernel: 86030 pages reserved
Jun 14 22:53:19 localhost kernel: [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
Jun 14 22:53:20 localhost kernel: [ 2368]     0  2368  1796765  1370579    3421   367426             0 sync_gateway
Jun 14 22:53:20 localhost kernel: Out of memory: Kill process 2368 (sync_gateway) score 898 or sacrifice child
Jun 14 22:53:20 localhost kernel: Killed process 2368 (sync_gateway) total-vm:7187060kB, anon-rss:5482280kB, file-rss:36kB
```

**Comment by raghusarangapani** [comment]
Filed https://github.com/couchbase/sync_gateway/issues/2651 for the above issue

**Comment by raghusarangapani** [comment]
We need to add a functional test for high SG revs_limit.

Refer couchbase/sync_gateway#2651 for more details about the issue

**Comment by sridevi-15** [comment]
Sync up with @adamcfraser regarding memory limits

**Comment by raghusarangapani** [comment]
Based on my last update, SG gets killed due to OOM well before we hit the Xattrs memory limits. Awaiting further instructions from @adamcfraser

**Comment by adamcfraser** [comment]
If you're hitting OOM before reaching the size limit on the system xattr, I think that qualifies as successful validation that we're not going to hit the xattr size limit (at least not before hitting other issues).

**Comment by raghusarangapani** [comment]
Closing based on Adam's comment above.
