### ISSUE TITLE
XATTRs: Test tombstone handing

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1054]
- Set CB Server 'purge time',
- Create a tombstone doc

- verify doc is available until purge time is reached
- restart sg
-verify sg admin API with _raw and verify that it shows 404 error

**Comment by adamcfraser** [comment]
https://developer.couchbase.com/documentation/server/5.0/rest-api/compaction-rest-api.html

**Comment by sethrosetter** [comment]
Possibly pull them into longevity / system test

**Comment by sethrosetter** [comment]
Could be manually tested.

**Comment by raghusarangapani** [comment]
Assigning to @adamcfraser for further instructions on what needs to be tested.
