### ISSUE TITLE
XATTRs scenario with Sync Gateway and XDCR

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1066]
Need input from @ssmotra.

**Comment by sethrosetter** [comment]
We should leverage the https://github.com/couchbaselabs/sequoia framework if possible

**Comment by sethrosetter** [comment]
- [ ] 2 clusters with master-master XDCR?
- [ ] 2 clusters with master-slave XDCR?
- [ ] Verify data correctness
- [ ] Shared docs

**Comment by sethrosetter** [comment]
Some sample scenarios with more information:
- Cluster One (SG) <- XDCR -> Cluster Two (SDK), using a shared bucket
  - Verify that the data is intact

- Need SG configs
- Need example http requests to SG
  - CRUD

**Comment by andreibaranouski** [comment]
http://qa.sc.couchbase.com/view/All/job/cen006-P0-converg-xattrs-vset0-03-xdcr-sg/
https://github.com/couchbase/testrunner/blob/master/conf/py-xdcr-xattr-sg.conf
