### ISSUE TITLE
XATTRs: Sync function scenarios for XATTRs

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1079]
Need to review with @adamcfraser

**Comment by sethrosetter** [comment]
Moving this out of DP per conversation with Adam

**Comment by sethrosetter** [comment]
Limit to new functionality - `IsImport`?

**Comment by sethrosetter** [comment]
Need to sync with @adamcfraser when starting this ticket.

**Comment by adamcfraser** [comment]
Closing this as IsImport has been descoped for 1.5.
