### ISSUE TITLE
Run func and perf tests against sync gateway built with -race flag

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#1082]

**Comment by tleyden** [comment]
Perf test in progress:

http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/540/console

TODO: extract `-race` into Jenkins param.  Just hardcoded it for the time being.

**Comment by sethrosetter** [comment]
PR up for changes to enable this with the functional tests - https://github.com/couchbaselabs/mobile-testkit/pull/1083

**Comment by sethrosetter** [comment]
This is going to be tougher than expected. The first run timed out - http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/341/

- [ ] Updated the timeout on the jenkins job. 
- [ ] Updated the logs to collect on every test
- [ ] Updated script to look through the logs

**Comment by tleyden** [comment]
In [sync-gateway-perf-test/542/](http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/542/), which has the `-race` flag enabled and was running against SG commit https://github.com/couchbase/sync_gateway/commit/5bb66efa523a2440642729ba5faebfef96fd2696, I'm seeing the following races.

## Sync Gateway

- [(*SyncSequenceClock).SetMaxSequence()](https://gist.github.com/tleyden/6027293cf2d38aab317913830b854dd2) 

## Sync Gateway Accel

- [(*KvChangeIndexWriter).Init.func3.1()](https://gist.github.com/tleyden/f6a59c811f3319b92299679592ef358d) 
- [gomemcached/debug.(*mcops).count()](https://gist.github.com/tleyden/0a69e6798278dadc998712965d96bcb3)

**Comment by tleyden** [comment]
> (*SyncSequenceClock).SetMaxSequence()

This looks like concurrent access to a *slice*, so it will probably fly under the radar since the go 1.6 runtime detection is limited to maps.  

> (*KvChangeIndexWriter).Init.func3.1()

Looks like it's coming from [this code](https://github.com/couchbaselabs/sync-gateway-accel/blob/master/indexwriter/kv_change_index_writer.go#L169-L171), which is a `time.Time` struct rather than a map.

> gomemcached/debug.(*mcops).count()

This is [reading from a slice rather than a map](https://github.com/couchbase/gomemcached/blob/master/debug/mcdebug.go#L58)

**Comment by tleyden** [comment]
In [sync-gateway-perf-test/543](http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/543/) against `release/1.4.0.2` sg commit https://github.com/couchbase/sync_gateway/commit/8fa08fb27b19c1b6a0ccb86a27c3b91b7fb806d8 I'm seeing a new data race:

## Sync Gateway

- [db.(*changeListener).NotifyCheckForTermination()](https://gist.github.com/tleyden/d0b0e1c3e9ae52db150d36db98513b8c)

## Sync Gateway Accel

No new races compared to previous run

**Comment by adamcfraser** [comment]
For the last one - db.(*changeListener).NotifyCheckForTermination() - we shouldn't be using changeListener.terminateCheckCounter directly.  We should go through a locking accessor, like we do in changeListener.CurrentCount().

**Comment by tleyden** [comment]
| Function/Method Call | Gist | Product  | 
| ------------- | ------------- | ------------- |
| (*SyncSequenceClock).SetMaxSequence()  | https://gist.github.com/tleyden/6027293cf2d38aab317913830b854dd2 | Sync Gateway | 
| (*KvChangeIndexWriter).Init.func3.1()  | https://gist.github.com/tleyden/f6a59c811f3319b92299679592ef358d | SG Accel | 
| gomemcached/debug.(*mcops).count()  | https://gist.github.com/tleyden/0a69e6798278dadc998712965d96bcb3 | SG Accel | 
| db.(*changeListener).NotifyCheckForTermination()  | https://gist.github.com/tleyden/d0b0e1c3e9ae52db150d36db98513b8c | Sync Gateway |

**Comment by sethrosetter** [comment]
Topo specific tests

| Function/Method Call  | Gist | Product |
| ------------- | ------------- | ------------- |
| github.com/couchbase/sync_gateway/rest.(*ServerContext).startShadowing()  | Content Cell  | SG |
| github.com/couchbase/go-couchbase.(*Bucket).UpdateBucket() | Content Cell  | go-couchbase |
| github.com/couchbase/go-couchbase.(*TapFeed).connectToNodes()  | Content Cell  | go-couchbase |
| github.com/couchbase/go-couchbase.(*TapFeed).closeNodeFeeds()  | Content Cell  | go-couchbase  |
| github.com/couchbase/go-couchbase.(*TapFeed).Close() | Content Cell  | go-couchbase  |

**Comment by tleyden** [comment]
No more work pending on this
