### ISSUE TITLE
Run perf tests with -race

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#1091]
Perf test equivalent of https://github.com/couchbaselabs/mobile-testkit/issues/1082

Should just involve updating the jenkins jobs

**Comment by sethrosetter** [comment]
@tleyden. This is done right?

**Comment by sethrosetter** [comment]
Closing as duplicate of #1088

**Comment by tleyden** [comment]
No, this never got done.  I temporarily updated the jenkins job, but then rolled back the changes because I didn't do it in a clean way.

What's needed:

- Add new boolean param to the jenkins job "Detect Data Races"
- Update the jenkins shell script to pass this flag to the provisioning step

**Comment by sethrosetter** [comment]
@tleyden Can we track this with #1088?

**Comment by tleyden** [comment]
Duplicate of #1088
