### ISSUE TITLE
All base cc tests failing on jenkins

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#1096]
[cen7-sync-gateway-functional-tests-base-cc/379/](http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/379/) is showing 127 failures

I noticed this when trying to validate a [recent SG change](https://github.com/couchbase/sync_gateway/pull/2450#issuecomment-291290447)

**Comment by sethrosetter** [comment]
Please target a 4.6.1 for Server. There were recent bucket changes that broke out provisioning. @raghusarangapani has been working on a fix since yesterday.

**Comment by raghusarangapani** [comment]
This server version has RBAC enabled as @sethrosetter mentioned. Don't target 5.0.0 for now

**Comment by tleyden** [comment]
Ok thanks for the heads up.  http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/383/ is in progress and seems to be working so far

**Comment by tleyden** [comment]
This test failed in the same way, even though it was using couchbase server 4.6.1:

http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-di/350/parameters/

**Comment by tleyden** [comment]
The base cc job is working now
