### ISSUE TITLE
CollectionError: could not pull logs

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#1113]
In http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/438/artifact/results/report.html, I'm seeing:

```
        status = ansible_runner.run_ansible_playbook("fetch-sync-gateway-logs.yml")
        if status != 0:
>           raise CollectionError("Could not pull logs")
E           CollectionError: Could not pull logs
```

**Comment by tleyden** [comment]
Ditto for http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-di/402/artifact/results/report.html

**Comment by sethrosetter** [comment]
@tleyden This is expected if a service fails to launch and no logs are available. Please reopen if you hit this again due to a non provisioning error

**Comment by tleyden** [comment]
Ok, but this is really confusing.  Can the error be "Provisioning failed" in that case?
