### ISSUE TITLE
Separate jenkins job(s) for SG master functional tests

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/mobile-testkit#1115]
It's difficult to analyze the history of the SG functional tests against master, because the results are interleaved with ad-hoc functional test runs, and CBS validation runs.    This makes it easier to miss when a change on master has broken the tests, and harder to work back in time to identify when a given test started failing.

It would be ideal to have one set of functional tests jobs that are only used for running against master, and another that's used for server validation or ad-hoc testing.

**Comment by tleyden** [comment]
Agreed, but I think we should figure out a way without duplicating the jenkins jobs, since that increases maintenance

**Comment by adamcfraser** [comment]
@tleyden That's a reasonable concern - if we had some sort of reporting dashboard that filtered the list down to the jobs triggered by the sync gateway build job (with links to the underlying functional test runs), that would also work.

**Comment by sethrosetter** [comment]
@adamcfraser @raghusarangapani hooked this up. Perhaps we can make use of it. http://greenboard.hq.couchbase.com/#/mobile/1.4.1/0003

**Comment by tleyden** [comment]
@sethrosetter what about walking us through the greenboard stuff at an upcoming show n' tell?  I'm not familiar with it at all

**Comment by adamcfraser** [comment]
@tleyden Going to leave this open until we get that walkthrough.  I'm not yet convinced that greenboard is addressing the requirements listed above.

**Comment by sethrosetter** [comment]
@raghusarangapani Can you demo Greenboard to @adamcfraser and see if it solves his issues?

**Comment by raghusarangapani** [comment]
I discussed this issue with Adam. Adam says that greenboard view is fine for now. Closing.
