### ISSUE TITLE
Limit Jenkins view in results graph

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1140]
There are currently too many builds in the jenkins results graph for the sync gateway functional tests. 

- [x] Talk to Tony on server QE and see what they do. Are builds discarded after a period of time? We should match theif behavior
- [x] Update the Jenkins jobs

**Comment by raghusarangapani** [comment]
Every server jenkins job has different "days to keep" like 10, 20, 30 etc. I set all our jobs to 30 days.

**Comment by sethrosetter** [comment]
@raghusarangapani. Then are the results discarded? Do they have any rolling backup?

**Comment by raghusarangapani** [comment]
The builds are discarded by jenkins. Jenkins does not back up. Tony says that they prefer to keep jobs around only for 4 days without any backup. They have a cron job that deletes anything more than 5 days old.

**Comment by sethrosetter** [comment]
Alright. Sounds good. Thanks!
