### ISSUE TITLE
Update add_bulk_docs to check for the status of every doc

### ISSUE THREAD

**Issue by raghusarangapani** [couchbaselabs/mobile-testkit#1169]
Currently, when we add bulk docs, we only check for HTTP error code. It is possible that when we add a 1000 docs, 999 got added and 1 failed but the API still returns a 200 OK. We need to go through the response for adding the bulk docs and verify if all docs got added successfully.

**Comment by sethrosetter** [comment]
Fixed via c9c2493d7a0ede951c30c952377075d32bf9431d
