### ISSUE TITLE
Add usernames to SG configs

### ISSUE THREAD

**Issue by raghusarangapani** [couchbaselabs/mobile-testkit#1180]
With RBAC enabled for 5.0 CBS, we made a change to make bucket authentication default for all buckets. This caused tests to fail with SG-1.3.1 and SG-1.2. SG-1.4 builds implicitly use bucket name as the username but that does not seem to be the case with the older SG builds. Thee workaround for this issue is to explicitly specify username/password for the bucket in the SG config.

**Comment by tleyden** [comment]
> This caused tests to fail with SG-1.3.1 and SG-1.2. SG-1.4 builds implicitly use bucket name as the username but that does not seem to be the case with the older SG builds.

Which couchbase server version?

Has this change been tested w/ both Couchbase server 4.x and 5.x versions?  (I have no reason to think it wouldn't work, just want to confirm)

**Comment by raghusarangapani** [comment]
Here is a run with 4.6.1:
http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/521/

5.0 runs should get kicked off soon by jenkins
