### ISSUE TITLE
Reenable "test_rebalance_sanity"

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1200]
Only if SG version >= 1.5

Since we are now using gocb, this should be fixed

**Comment by sethrosetter** [comment]
This is in https://github.com/couchbaselabs/mobile-testkit/pull/1347
- [ ] Run the reenabled tests locally and make sure they work before merging. The rebalance test is currently failing due to a test issue.

**Comment by sridevi-15** [comment]
This test is reenabled after adding multiple url support. It is in branch now, sent pull request to Raghu
