### ISSUE TITLE
pytest: error: unrecognized arguments: --xattrs in cen7-sync-gateway-functional-tests-base-cc

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#1201]
In [cen7-sync-gateway-functional-tests-base-cc/619](http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/619/console) it's hitting this error:

```
02:28:35 Running ALL tests+ pytest --ci --xattrs --mode=cc --server-version=5.0.0-2873 --sync-gateway-version=1.5.0-383 testsuites/syncgateway/functional/tests/
02:28:36 usage: pytest [options] [file_or_dir] [file_or_dir] [...]
02:28:36 pytest: error: unrecognized arguments: --xattrs
02:28:36   inifile: /var/jenkins/workspace/cen7-sync-gateway-functional-tests-base-cc/pytest.ini
02:28:36   rootdir: /var/jenkins/workspace/cen7-sync-gateway-functional-tests-base-cc
02:28:36 Build step 'Execute shell' marked build as failure
```

Looks like possibly a jenkins config error, or am I running an invalid config?

**Comment by tleyden** [comment]
Ditto for [cen7-sync-gateway-functional-tests-topology-specific-cc/493](http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-topology-specific-cc/493/console)

**Comment by sethrosetter** [comment]
@tleyden That param only exists on a branch. If you are targeting master, you will hit this.

**Comment by sethrosetter** [comment]
It will work once this is in - https://github.com/couchbaselabs/mobile-testkit/pull/1198
