### ISSUE TITLE
XATTRs: Test view compaction

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1203]
Need to sync up with @adamcfraser about this.

**Comment by sethrosetter** [comment]
Per conversation with @adamcfraser:

1. Generate some tombstones
2. Execute a view query, see the tombstones
3. Wait for the tombstones to be purged (would require some way to set the metadata purge interval to a low value)
4. Execute a view query, see the tombstones
5. Run compaction
6. Execute a view query, ensure you don't see the purged tombstones

**Comment by sethrosetter** [comment]
The tricky part will be 3 (Not sure if this is possible)

**Comment by sethrosetter** [comment]
Looks like this used to be support (need to verify if it still works)
```
curl -v -X POST -u Administrator:password http://localhost:8091/diag/eval -d 'ns_bucket:update_bucket_props("sasl", [{purge_interval, 1 / (1* 30 * 60)}])'
```

**Comment by sethrosetter** [comment]
Look into:
```
exp_pager_stime
The cbepctl flush_param exp_pager_stime command sets the time interval for disk cleanup. Couchbase Server does lazy expiration, that is, expired items are flagged as deleted rather than being immediately erased. Couchbase Server has a maintenance process that periodically looks through all information and erases expired items. By default, this maintenance process runs every 60 minutes, but it can be configured to run at a different interval.
```
from https://developer.couchbase.com/documentation/server/current/cli/cbepctl/set-flush_param.html

**Comment by sethrosetter** [comment]
This might be the solute - POST to /pools/default/buckets/<bucket_name>/controller/unsafePurgeBucket

**Comment by raghusarangapani** [comment]
From the updates and conversation with Seth, no one seems to know how to set the purge interval manually. Awaiting further instructions from @adamcfraser
