### ISSUE TITLE
XATTRs: Test webhook triggers on import

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/mobile-testkit#1206]
When a document gets written via the SDK, then imported by Sync Gateway, it should trigger any webhook events configured in Sync Gateway.  The webhook should be triggered on import (not on the initial SDK write), and apply the usual webhook filtering.

I don't think this is covered by the current test suite - I expect the webhook tests are being run in xattr mode, but I don't think there are any tests that verify webhook events for SDK writes.

**Comment by sethrosetter** [comment]
- [ ] with / without filter
- [ ] hook event for create
- [ ] hook event for update
- [ ] hook event for delete
