### ISSUE TITLE
XATTRs: Test Mobile Opt-In

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1219]
Filter for mobile enabled docs
Subset of bucket docs
mobile enabled docs

**Comment by sridevi-15** [comment]
sync up with @adamcfraser  before start implementing .

**Comment by raghusarangapani** [comment]
Corresponding SG PR - https://github.com/couchbase/sync_gateway/pull/2755

**Comment by raghusarangapani** [comment]
Assigning to @adamcfraser  for further steps on what needs to be tested.

**Comment by adamcfraser** [comment]
We've added the ability to define an `import_filter` in the Sync Gateway config.  This is a javascript function that takes the doc as a parameter, and returns a boolean.  The function is executed any time an SDK write is being imported.  If the function returns false, the document will not be imported (i.e. will not be visible from mobile).

Need tests to validate execution of the import_filter for a variety of docs, and validation of document state post-filtering.

Commit notes here:
https://github.com/couchbase/sync_gateway/commit/8094cb09519cddc1aa5cba5c752c85bfb434abd7

Functional spec is here: https://docs.google.com/document/d/1XxLIBsjuj_UxTTJs4Iu7C7uZdos8ZEzeckrVc17y3sw

I expect we want functional tests for cases 1-5 in the functional spec.

**Comment by raghusarangapani** [comment]
@adamcfraser confirmed that there is decent unit test coverage of the import filter. This might not be the top priority if time is limited.
