### ISSUE TITLE
XATTRs: Test Upgrade

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1220]
Refer to Test Plan Google doc

**Comment by raghusarangapani** [comment]
We have dataset from the field. We should use that dataset to reflect customer upgrade scenario.

**Comment by raghusarangapani** [comment]
#### path 
   - syncgateway/upgrade/test_upgrade.py
#### inputs
   - upgrade type: docmeta -> docmeta, docmeta -> XATTRs
   - mode: cc or di
   - LiteServ version: 1.3 or 1.4
   - HA: Rolling upgrade or cluster down upgrade?
   
## Scenario
- Provision SG/SGAccel/Nginx using existing provisioning.
- Start 30 .net LiteServs
   - Why 30?
   - .NET Linux test runner jenkins node - More info needed
- Start push/pull replication between SG and LiteServ
- Load LiteServs with dataset from the field through the LiteServ REST api. 
   - Provide a way to scale the data up and down - need more info
- Start updating the dataset from the client, keep track of the updates you make.
   - Random doc updates?
   - Till the upgrade of all SGs are done?
- Upgrade SG/SGAccel
   - A new yml file might be needed for upgrade
   - Remove Sync Gateway from load balance - is it needed? seems like nginx can handle failover with  `proxy_next_upstream` and `proxy_connect_timeout` params.
   - Rolling upgrade: Stop SG Service one SG at a time.
   - Cluster down upgrade: Stop all SGs.
   - Upgrade SG/SGAccel one node at a time - ansible will take care of this
   - SG/SGAccel config changes for docmeta -> XATTRs only:
      - cc - Start 1 SG with import enabled, all with XATTRs enabled
      - di - All SGs with import enabled, all SGs with XATTRs enabled
   - Start SG service
   - Verify SG version through REST
   - Add back to load balancer - is it needed? seems like nginx can handle failover with  `proxy_next_upstream` and `proxy_connect_timeout` params.
- Stop doc updates.
- Verify data
   - Doc IDs? revisions? doc body? attachments?
   - Existing client.verify_docs_in_changes can be reused?
   - docmeta -> XATTRs - are there existing verification mechanisms using SDK?
- Scan logs for errors/panics
