### ISSUE TITLE
Run test_log_200mb[log_rotation] for release

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1222]
This has been disabled due to test framework error. We will need to run this for release.

**Comment by raghusarangapani** [comment]
Verified by running it locally - test passed on CentOS7

`pytest -s --timeout 1800 -k test_log_200mb --mode=cc --server-version=5.0.0-3497 --sync-gateway-version=1.5.0-538 testsuites/syncgateway/functional/tests`
