### ISSUE TITLE
SG-1.3.1 panics with the new SG config changes

### ISSUE THREAD

**Issue by raghusarangapani** [couchbaselabs/mobile-testkit#1225]
A recent change to the SG configs to add  "unsupported": {}, is causing SG 1.3.1 to panic. 1.3.1 does not support an empty "unsupported" block.

**Comment by tleyden** [comment]
@raghusarangapani thanks for calling that out.  I'm going to close this ticket as a duplicate, since #1240 has steps to repro and a link to an SG ticket
