### ISSUE TITLE
Mixed load performance testing

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#1236]
- [ ] Need long running test with updates
- [x] Enhance sgload to do multi-part docs w/ attachments
- [ ] Ability to test against a sync function that would reject some docs out of a bulk docs operation

**Comment by sethrosetter** [comment]
@tleyden Is this still a P1 high for 1.5?

**Comment by tleyden** [comment]
I don't think so.  Other folks on QE Perf team are apparently taking this one on.
