### ISSUE TITLE
Need upgrade paths defined for mobile

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1247]
We need a matrix defined of upgrade scenarios that we need to cover.

Which versions of SG before and after?
Which versions of Lite before and after?
What is the recommended way to upgrade?
What are the operations that we expect to happen / support during upgrade?
Define pass / fail criteria.

**Comment by djpongh** [comment]
Seth, I think this will have what you need:
 https://docs.google.com/document/d/1ptNyA4E-8CntQoRyzmLqJ_DY6wV-Lb-mlY54I3lzQVQ/edit#heading=h.kkk0ixiz9dae
