### ISSUE TITLE
Xattrs / Changes feed functional test

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#1249]
1. Start sync gateway with xattrs and import enabled
1. Start changes feed
1. Perform mutations (Create set of docs, Update the set of docs) via python server sdk
1. Verify all mutations appear on changes feed as expected
   - (Create) Check the doc id / content is what you added via the server SDK
   - (Update) Check the revision / new content
1. Perform mutations via SG REST API (MobileRestClient)
1. Verify all mutations appear on changes feed as expected
1. Verify all mutations appear on changes feed as expected
   - (Create) Check the doc id / content is what you added via the server SDK
   - (Update) Check the revision / new content

Related test https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/syncgateway/functional/tests/test_xattrs.py#L967-L1211

**Comment by sethrosetter** [comment]
There is one tricky situation. If The DCP feed may batch SDK mutations in bulk so we may multiple mutations show up as one rev from the Sync Gateway perspective.

**Comment by sethrosetter** [comment]
![Untitled Diagram.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55e9d9d60fe681110009b8b0/125516c66e82c728ace21e0d46dd9a8e2a968fac8ba99b4aa55ae29524046b313916ac217586f76ae5002e560b584caf440b5d4da8ab8c23a1b03c718b585db9d3644d68d47f40f2ecdd42e64bef62994597b5bd804dc5e83c27e08d8e4f3c1706199bb2.png)
