### ISSUE TITLE
Run longevity perf test

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1255]

**Comment by raghusarangapani** [comment]
The 2 day tests have been started

**Comment by raghusarangapani** [comment]
The 3 day test with xattrs is complete.
The 3 day test without xattrs is ongoing.

**Comment by raghusarangapani** [comment]
The 3 day test without xattrs is done, 1 ticket was filed - https://github.com/couchbase/sync_gateway/issues/2688
