### ISSUE TITLE
System Test #1

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1264]
1. Start with 1,000,000 -> 100,000,000 1K docs in Couchbase Server (5.0) Bucket, Can we preload this? 
2. Start Sync Gateway with import enabled (xattrs only)
3. Write 1,000 1K docs with attachments to Server and continually update to 1,000,000 1K docs with attachments using 180 users concurrently
  - 60 users have channel filters
    - 20 using looping normal _changes
    - 20 using looping longpoll _changes
    -20 using continuous _changes
  - 60 users with shared channels
    -  20 using looping normal _changes
    - 20 using looping longpoll _changes
    - 20 using continuous _changes
  - 60 users with unique channels
    - 20 using looping normal _changes
    - 20 using looping longpoll _changes
    - 20 using continuous _changes
4. Update docs continuously for a time period
5. Define a sync function to grant / revoke access to all channels when writing specific docs (grant_docs, revoke_docs)
6. Create 20 users to create random (grant_docs, revoke_docs) docs throughout the entire scenario
7. Create 10 users to insert conflicts ?
 
### Pass criteria (v1):
- Runs for a day
- Nothing crashes
8. No panics / unexpected errors in the logs

**Comment by raghusarangapani** [comment]
The below steps were de-scoped after a conversion between Seth and Adam:

5. Define a sync function to grant / revoke access to all channels when writing specific docs (grant_docs, revoke_docs)
7. Create 10 users to insert conflicts ?
