### ISSUE TITLE
Run Sync Gateway Tests on Windows

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1266]

**Comment by sethrosetter** [comment]
I was just looking at metrics on the Windows box. The CPU seems pretty high. Next time you run it, do you think you can monitor the machine and see if anything seems strange?

<img width="694" alt="screenshot 2017-06-27 14 31 53" src="https://user-images.githubusercontent.com/1365736/27611069-a44625fc-5b45-11e7-8686-c337fcb7c5e7.png">

**Comment by raghusarangapani** [comment]
This windows VM has only core assigned to it. The centos VMs have 4 cores. The net time I run the tests, Ill set the cores to 4.

**Comment by raghusarangapani** [comment]
Setting the VM to 4 cores fixed the issue
<img width="577" alt="screen shot 2017-08-01 at 9 41 25 am" src="https://user-images.githubusercontent.com/24398601/28836415-aaa02060-769d-11e7-8453-10d717586581.png">

**Comment by raghusarangapani** [comment]
The SG functional tests were run with and without xattrs, there were a few failures. Logged a tracking ticket for further investigation - https://github.com/couchbaselabs/mobile-testkit/issues/1341
