### ISSUE TITLE
Run security scans against SG using Qualys tools

### ISSUE THREAD

**Issue by raghusarangapani** [couchbaselabs/mobile-testkit#1280]
Run security scans against SG using Qualys tools

**Comment by sridevi-15** [comment]
Zap tool : 
Did security scans to following versions 
    sync-gateway -> 1.5
    couchbase-server -> 5.0.0-3217(beta version)
Worked on security scans on VMs using Zap tool.
Tested with exposed end points and scanned with admin and non admin interfaces
      /db/doc
     /db
    /db/_bulk_docs
    /db/changes
   /db/_oidc
Did port scanning on sync-gateway VM using nmap
As Zap tool does only get calls while scanning, I did some post actions on admin interface and added zap as proxy on browser and got some post and Put calls from browser on zap and ran scan with all end points 

Qualys tool :
     As Qualys tool accept only public ips, sync-gateway and CBS were set up on AWS instance 
    Also Set up sync-gateway to port 80 to publish ip as public to run on Qualys tool.
       Areas covered
         - security vulnerabilities
         - web application scanning
        - port scanning
       - malware detection

Tested on admin and non admin interface with port 80 

Here is the ticket that caught during all security scans
https://github.com/couchbase/sync_gateway/issues/2711

**Comment by sridevi-15** [comment]
[sync-gateway-1.5-xcontentTypeMissing.html.zip](https://github.com/couchbaselabs/mobile-testkit/files/1143362/sync-gateway-1.5-xcontentTypeMissing.html.zip)

https://freescan.qualys.com/freescan-front/module/freescan/#scan_report?id=286373&
https://freescan.qualys.com/freescan-front/module/freescan/#scan_report?id=286369&
https://freescan.qualys.com/freescan-front/module/freescan/#scan_report?id=286367&

**Comment by sridevi-15** [comment]
[sycn-gateway-non-admin-scan.pdf](https://github.com/couchbaselabs/mobile-testkit/files/1146574/sycn-gateway-non-admin-scan.pdf)
[sync-gateway-admin-db-endpoint-scan.pdf](https://github.com/couchbaselabs/mobile-testkit/files/1146575/sync-gateway-admin-db-endpoint-scan.pdf)
[sync-gateway-admin-interface-scan.pdf](https://github.com/couchbaselabs/mobile-testkit/files/1146576/sync-gateway-admin-interface-scan.pdf)
