### ISSUE TITLE
error running the file: utilities/generate_cluster_configs_from_vagrant_hosts.py

### ISSUE THREAD

**Issue by sridevi-15** [couchbaselabs/mobile-testkit#1293]
Run this command on root folder and you get an error on generate_clusters_from_pool. 

python utilities/generate_cluster_configs_from_vagrant_hosts.py --private-network --create

generate_clusters_from_pool is expecting 2 parameters  , but this file is called with 1 parameter.

Here is the error : 
Getting ip addresses from running vagrant vms ...
Connection to 127.0.0.1 closed.
host: host1 ip: 192.168.33.10
Connection to 127.0.0.1 closed.
host: host2 ip: 192.168.33.11
Connection to 127.0.0.1 closed.
host: host3 ip: 192.168.33.12
Connection to 127.0.0.1 closed.
host: host4 ip: 192.168.33.13
Connection to 127.0.0.1 closed.
host: host5 ip: 192.168.33.14
Writing 'resources/pool.json' ...
Generating cluster_configs ...
Traceback (most recent call last):
  File "utilities/generate_cluster_configs_from_vagrant_hosts.py", line 113, in <module>
    generate_cluster_configs_from_vagrant(opts.private_network, opts.public_network, opts.public_network_ethernet)
  File "utilities/generate_cluster_configs_from_vagrant_hosts.py", line 77, in generate_cluster_configs_from_vagrant
    generate_clusters_from_pool(pool_file)
TypeError: generate_clusters_from_pool() takes exactly 2 arguments (1 given)

It creates pool.json with ip addresses, but it fails while generating clusters.

Ran the file directly from libraries/utitiliest/generate_clusters_from_pool.py and worked fine.

**Comment by raghusarangapani** [comment]
Issue seems to be that there is no default value for `use_docker` - `def generate_clusters_from_pool(pool_file, use_docker):`

**Comment by raghusarangapani** [comment]
This is now fixed
