### ISSUE TITLE
Unit integration tests against Couchbase Server

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#1310]
## Modes

* SG Xattr
* SG Non-xattr
* SG accel Xattr
* SG accel non-xattr

## Existing Jenkins Job

There is an existing jenkins job in uberjenkins under the **Build** tab: http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway/configure

Example job runs:

- [without xattrs, against couchbase server 4.x](http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway/138/parameters/)
- [with xattrs, against couchbase server 5.x](http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway/137/parameters/)

You can ignore the `RUN_TESTS` functionality, which runs tests against Walrus 

## Steps 

- Build sync gateway (the build team can eventually emit a test binary)
- Startup appropriate couchbase server version (using Sequoia or whatever makes sense)
- Run tests with appropriate env variables (xattrs / no xattrs) and couchbase url -- see Jenkins job

**Comment by sridevi-15** [comment]
[] Run the test_integration.sh locally -> code is couchbase/sync-gateway
[] Add steps to provision CBS and sync-gateway with specific commit
[] Setup cluster for sync-gateway.

**Comment by tleyden** [comment]
@sridevi-15 just as a heads up, you might see some sporadic failures in the actual tests, it's a known issue logged in https://github.com/couchbase/sync_gateway/issues/2726

**Comment by sethrosetter** [comment]
We are hitting issues when running with port bindings in docker to localhost:8091. Next steps:
- [ ] We need a docker container that can build SG source and run tests in a docker context.
- [ ] Start up container in the same network as the server cluster

**Comment by tleyden** [comment]
This one is done
