### ISSUE TITLE
Test reporting for view unavailable

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1317]
There will be a better error message when a view times out. We need to add a functional test or support in the system test.

Ways to check:
- [ ] Create a user while views are indexing (crank down view timeout on Server side)
- [ ] Hit changes from admin API to initiate backfill

**Comment by sethrosetter** [comment]
Use existing System Test to try to repro this and document the parameters to start.

**Comment by raghusarangapani** [comment]
Manually verified with CBS 4.6.2, SG 1.4.1.1-8:

- Loaded 500,000 docs to the CBS through SG. 
- Stopped SG.
- Deleted the views on CBS.
- Started SG.
- Issued a query to _all_docs.

```
~ » curl http://192.168.33.20:4985/db/_all_docs
{"rows":[
{"error":"Service Unavailable","reason":"Timeout performing ViewQuery - could indicate that views are still reindexing"}% 
```
