### ISSUE TITLE
Add support on mobile testkit framework to run sync gateway tests on Red hat linux

### ISSUE THREAD

**Issue by sridevi-15** [couchbaselabs/mobile-testkit#1328]
Putting a place holder to add support on mobile-testkit to run sync gateway tests on Red hat linux

Should provide scripts to set up Red hat on  VMS and on Docker 
Should provide scripts to set up Couchbase server , sync gateway , accelerator -> We can make use of existing scripts and specify platform name to set up.

**Comment by raghusarangapani** [comment]
This is done - https://github.com/couchbaselabs/mobile-testkit/pull/1343
