### ISSUE TITLE
Default Couchbase Server version not passed to downstream job

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1335]
In this job, http://uberjenkins.sc.couchbase.com/view/01%20QE-Matrix/job/_sync-gateway-upstream/, the default value is currently `4.6.2` but all of the downstream jobs are getting `4.6.1`. This needs to be looked at.

**Comment by sridevi-15** [comment]
I looked at this job. all downstream jobs are now picking up the value passed from parent job.
