### ISSUE TITLE
Update testkit to take list of server urls in sg configs

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1338]
To support testing https://github.com/couchbase/sync_gateway/issues/1019

- [ ] https://github.com/couchbase/sync_gateway/issues/2576 should be re-verified (test might need to be re-enabled)

**Comment by tleyden** [comment]
There is a PR up for this change now: https://github.com/couchbase/sync_gateway/pull/2772

**Comment by tleyden** [comment]
Once this is completed, https://github.com/couchbase/sync_gateway/issues/2576 should be re-verified (test might need to be re-enabled)

**Comment by tleyden** [comment]
PR #2722 has been closed.

Here are the pending docs on how to configure Sync Gateway for multiple server urls:

https://github.com/couchbaselabs/couchbase-mobile-portal/issues/791

**Comment by adamcfraser** [comment]
All functional tests related to Couchbase server failover and rebalance all need to be updated to run with multiple server URLs.
