### ISSUE TITLE
Use couchbases:// instead of https:// in SSL tests

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#1368]
https://github.com/couchbase/sync_gateway/issues/2496 was fixed by https://github.com/couchbase/sync_gateway/commit/271f32db0826c94aa6920671e61ccdcf44d5e9ab

**Comment by raghusarangapani** [comment]
With SSL enabled, SG config should have couchbases if SG version >= 1.5 and https if SG version < 1.5

**Comment by tleyden** [comment]
Pending doc changes: https://github.com/couchbaselabs/couchbase-mobile-portal/issues/791

**Comment by sridevi-15** [comment]
Increased the weight as bunch of tests should support to run 
couchbases with port
couchbases without port
couchbase without port

**Comment by adamcfraser** [comment]
Based on https://github.com/couchbase/sync_gateway/issues/3659, we still aren't doing couchbases:// testing in our functional test suite, which is a gap we need to close.

@sridevi-15 Can we prioritize this issue?
