### ISSUE TITLE
Remove the unsupported section in SG configs once xattrs is supported

### ISSUE THREAD

**Issue by raghusarangapani** [couchbaselabs/mobile-testkit#1375]
Corresponding SG ticket - https://github.com/couchbase/sync_gateway/issues/2797

We have to modify all SG configs to remove the unsupported section once enabling xattrs is supported.

**Comment by adamcfraser** [comment]
Enabling xattrs is now done using the `enable_shared_bucket_access` flag in the database config.  

Sample config showing usage here:
https://github.com/couchbase/sync_gateway/blob/master/examples/config-xattr.json

**Comment by raghusarangapani** [comment]
@adamcfraser Is "import_docs": "continuous" is still valid?

**Comment by raghusarangapani** [comment]
Never mind, just saw it in the example usage.
