### ISSUE TITLE
Run Gateload test with alternate sync function including access() calls

### ISSUE THREAD

**Issue by zgramana** [couchbaselabs/mobile-testkit#139]
Current Gateload test uses a generic Sync Function. To get a better range on performance, we need another test that will include occasional calls to `access`. 

Here is an illustration:
This can be done by including a unique integer in each document revision sent to Sync Gateway. The sync function can then wrap calls to `access` in this sort of a conditional block:
```javascript
  if (doc.counter % 50 == 0) {
    access(doc['target_user'], doc['_id']);
  }
```
Ideally, the modulus operand would be parameterized and configurable in a Jenkins job.

 >  Note: some of the work for the above example was done in https://github.com/couchbase/sync_gateway/issues/825, which called `access` on every sync function invocation.

**Comment by zgramana** [comment]
Last priority after mini-matrix.

**Comment by tleyden** [comment]
@sethrosetter here's an example Gateload config to add the target_user field:

"AddDocToTargetUser": true

**Comment by sethrosetter** [comment]
covered by #609
