### ISSUE TITLE
Bug verification

### ISSUE THREAD

**Issue by raghusarangapani** [couchbaselabs/mobile-testkit#1392]
Have to verify the below issues:

- [x] https://github.com/couchbase/sync_gateway/issues/2197
- [x] https://github.com/couchbase/sync_gateway/issues/2799
- [x] https://github.com/couchbase/sync_gateway/issues/2810
- [x] https://github.com/couchbase/sync_gateway/issues/2576
- [x] https://github.com/couchbase/sync_gateway/issues/2682
- [x] https://github.com/couchbase/sync_gateway/issues/2780
- [x] https://github.com/couchbase/sync_gateway/issues/1019

**Comment by sridevi-15** [comment]
https://github.com/couchbaselabs/sync-gateway-accel/issues/156  is removed as part of bug verification as it is not part of 1.5.
