### ISSUE TITLE
Test Lab Infrastructure enhancements

### ISSUE THREAD

**Issue by ashvindersingh** [couchbaselabs/mobile-testkit#146]
Need more devices and mac hardware to test and certify release. Currently we are limited to one iphone-5c and android device. As we move forward we would need to test against different devices and or android os versions and iOS versions. Also need to make sure couchbase lite software is compatible with older android and iOS releases.

**Comment by tleyden** [comment]
We should consider looking into [AWS Device Farm](https://aws.amazon.com/device-farm/) for this.

**Comment by sethrosetter** [comment]
Closing this as we have defined a support matrix and are using that to track Device / OS in our testing matrix.
