### ISSUE TITLE
Remove sleep delays in all functional tests

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#167]
Rather than doing sleep delays, which causes problems such as https://github.com/couchbaselabs/sync-gateway-testcluster/issues/161, we should have a way for the functional tests to block until things are expected to show up in the _changes feed -- some sort of admin level api that gives visibility into the channel index.

**Comment by sethrosetter** [comment]
New robot centric tests do not use sleeps. Should we keep this open to resolve technical debt or can I close this?

**Comment by sethrosetter** [comment]
I haven't seen a problem with this. Also all new test use polling with timeout. Please reopen  if you have a problem.
