### ISSUE TITLE
Get Android Integration tests stable for 1.2

### ISSUE THREAD

**Issue by ashvindersingh** [couchbaselabs/mobile-testkit#169]

**Comment by ashvindersingh** [comment]
@andreibaranouski assigning this to you as you are already working on it.

**Comment by sethrosetter** [comment]
Done via - 
http://qa.sc.couchbase.com/view/mobile/job/mac-android-node-js-tests-cb/
http://qa.sc.couchbase.com/view/mobile/job/mac-android-node-js-tests-walrus/
