### ISSUE TITLE
10K pushers / 10K pullers

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#183]
10k pushers /10k pullers per cluster
30 min test run time

Hardware specs
3 Couchbase Servers - c3.2xlarge
sync_gateway - c3.2xlarge
gateload - c3.2xlarge

## 8 IR / 1 IW

![gateload_expvars](https://cloud.githubusercontent.com/assets/1365736/12069512/602143e2-afe9-11e5-80e2-df68618de0a8.png)
![sync_gateway_expvars](https://cloud.githubusercontent.com/assets/1365736/12069513/628e7b5e-afe9-11e5-8fa9-9dae8b6ad605.png)
![sync_gateway_machine_stats](https://cloud.githubusercontent.com/assets/1365736/12069514/643117be-afe9-11e5-84bd-955780046da5.png)

## 2 IR / 2 IW

Full results - https://s3.amazonaws.com/sync-gateway-logs/10k-10k-2IR-2IW_2015-12-31-15-45-47.zip

![gateload_expvars](https://cloud.githubusercontent.com/assets/1365736/12069286/8a8ec770-afdb-11e5-9dfc-6f6df5248ece.png)
![sync_gateway_expvars](https://cloud.githubusercontent.com/assets/1365736/12069287/901ee936-afdb-11e5-87e5-e34891a62ce7.png)
![sync_gateway_machine_stats](https://cloud.githubusercontent.com/assets/1365736/12069288/925fe0d8-afdb-11e5-9d85-5c7daa83311c.png)

**Comment by adamcfraser** [comment]
Issue https://github.com/couchbase/sync_gateway/issues/1405 filed for this.

**Comment by zgramana** [comment]
Let's try another run of 4:2 with the 4 SG nodes running on r3.2xlarge so we effectively vertically scale on RAM only.

**Comment by sethrosetter** [comment]
Will be revisited as part of the 1.4 performance matrix
