### ISSUE TITLE
Add functional test to exercise pass-thru view query behavior

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#241]
Sync Gateway has the feature to pass-thru calls to couchbase server views.  It's a very powerful and useful feature.  I don't know if this is being tested at all by our functional tests (or integration tests).
- [Open issue: Pass-thru view query is failing](https://github.com/couchbase/sync_gateway/issues/1493)
- [Documentation on Sync Gateway views](http://developer.couchbase.com/documentation/mobile/1.1.0/develop/guides/sync-gateway/accessing-cb-views/creating-and-using-a-view/index.html)

**Comment by tleyden** [comment]
As it turns out, this might be a more difficult test than originally anticipated:

1. Install view on SG 1.1.1 port 4985 via REST api call
1. Shutdown SG 1.1.1
1. Start SG 1.2.0-rc0 pointed to same couchbase server
1. Query view created in step 1 via SG 1.2.0-rc0 REST api 
1. Assert that return code is not a 500 error

**Comment by sethrosetter** [comment]
@tleyden @zgramana  Is this required for 1.2? Right now targeted installs are not supported in the provisioning and would require a fair amount of heavy lifting. Should this just be a manual verification for 1.2 and automated for 1.3?

**Comment by adamcfraser** [comment]
Has been extensively verified manually by engineering for 1.2 - moving the automation task to 1.3.

**Comment by sethrosetter** [comment]
viewsOnlyJSON := {"name": "views_only",
              "server": "walrus:",
              "bucket": "views_only",
              "unsupported": {
                "user_views": {
                  "enabled":true
                }
              }
               }
