### ISSUE TITLE
Functional test for rebalance scenario

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#243]
Regression functional test to verify scenario https://github.com/couchbase/sync_gateway/issues/1286

**Comment by tleyden** [comment]
Similar issue: https://github.com/couchbase/sync_gateway/issues/1488#issuecomment-173035548

**Comment by sethrosetter** [comment]
Also #498

**Comment by sridevi-15** [comment]
Is it necessary and p1 high for 1.5? @adamcfraser

**Comment by sridevi-15** [comment]
This test is covered in this : https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/syncgateway/functional/topology_specific_tests/multiple_servers/test_multiple_servers.py
