### ISSUE TITLE
Fix limitation when deleting / recreating a single bucket

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#308]
Problem: if you create two buckets initially, then delete one bucket and recreate it, it will try to recreate the second bucket with the full RAM of the cluster but fail (since one bucket is still using half of the RAM)

**Comment by tleyden** [comment]
PR: https://github.com/couchbaselabs/sync-gateway-testcluster/pull/310

**Comment by sethrosetter** [comment]
@tleyden can this be closed?
