### ISSUE TITLE
Async request for listener test cluster

### ISSUE THREAD

**Issue by jamiltz** [couchbaselabs/mobile-testkit#322]
Not sure how test cluster for Sync Gateway handles async requests. It can be useful to:

- Wait for the doc count on each device to be equal
- Wait for the replication status to be idle before stopping replications

In broad terms, what are the code changes needed to wait for the responses of all async requests (one request per device) before proceeding to the next request in the test scenario?

**Comment by sethrosetter** [comment]
Done in new robot keywords
