### ISSUE TITLE
Investigate forestdb android failures for 1.2.1

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#356]
- [ ] not ok tests/cbl-database.js .......................... 22/53
- [x] not ok tests/cbl-document.js .......................... 22/63 (known issue)
- [ ] not ok tests/cbl-large-revisions-compact-revs-limit.js  53/87
- [ ] not ok tests/cbl-large-revisions-rev_cache_size.js .... 24/66
- [ ] not ok tests/cbl-revisions.js ......................... 53/65
- [x] not ok tests/cbl-simple-requests.js ..................... 2/4 (known issue)
- [ ] not ok tests/cbl-webhook_events_not_posted.js .......... 7/10

**Comment by sethrosetter** [comment]
not ok tests/cbl-database.js .......................... 22/53
Test output - https://gist.github.com/sethrosetter/c27a6f5e9fd027f5856f976e2d2a2ef6

not ok tests/cbl-document.js .......................... 22/63
Test output - https://gist.github.com/sethrosetter/82a0ca9fcf89dc3b1edc6e90f73e5a9a

not ok tests/cbl-large-revisions-compact-revs-limit.js 53/87 (Hangs on last changes request)
Test output - https://gist.github.com/sethrosetter/790231b8e58a58de06248360795bea27

not ok tests/cbl-large-revisions-rev_cache_size.js .... 24/66
Test output - https://gist.github.com/sethrosetter/e8dc88f387de04e29677f5b41fec4edd

**Comment by sethrosetter** [comment]
@hideki. After talking with @zgramana, these may be due to the fact that there is no way to open a forestdb database via the Android Listener currently.

**Comment by hideki** [comment]
From REST API, we can not specify storage type. But LiteServ for forestdb is coded to use forestdb. I think we need to investigate what root causes are.

**Comment by sethrosetter** [comment]
@hideki Good call. I will continue investigation tomorrow morning.

**Comment by sethrosetter** [comment]
known issues:
cbl-simple-requests.js - couchbase/couchbase-lite-java-core#1110
cbl-document.js - couchbase/couchbase-lite-android#249

**Comment by sethrosetter** [comment]
Seeing this in a lot of the failures:

```
response of http://localhost:8081/large-revisions-revslimit/large-revisions-revslimit_2?revs_info=true doens't contain _revs_info:null  HTTP/1.1
server: D. Rogatkin's TJWS with Android support (aka Acme.Serve)/Version 1.105, $Revision: 1.267 $,Couchbase Lite 1.2.1--1
date: Tue, 29 Mar 2016 20:41:58 GMT
mime-version: 1.0
transfer-encoding: chunked
connection: keep-alive
keep-alive: timeout=30, max=100
```

**Comment by sethrosetter** [comment]
and a lot of these:
```
uncompacted revision(s) remain by http://localhost:8081/large-revisions-revs_cache_size/large-revisions-revs_cache_size_2?revs_info=true
```

**Comment by sethrosetter** [comment]
- [ ] Need provide analysis to dev.

**Comment by sethrosetter** [comment]
### 1.2.0 Issues

cbl-database.js - 11 noncompacted revs failure - https://gist.github.com/sethrosetter/165aa8e48fd235bcde1573123bf59f8b

**Comment by sethrosetter** [comment]
These have been identified / triaged for 1.3.
