### ISSUE TITLE
Ability to run functional tests against local machine (as opposed to VM cluster)

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#36]
To make it easy for developers to run the functional tests locally (and offline if needed), there are only a few small changes needed.  For example:

I was able to run a functional test locally by commenting out this line in `test_single_user_single_channel.py`:

```

@pytest.mark.sanity
def test_1(cluster):

    # cluster.reset("sync_gateway_default_functional_tests.json")

    start = time.time()
    sgs = cluster.sync_gateways
```

What about adding a new flag `--skip-cluster-reset` to facilitate this?

**Comment by sethrosetter** [comment]
@tleyden. All the reset does is set the cluster to a clean state. It will:
- Detect all the server buckets and delete them
- Parse the sg configuration for buckets to create and create them
- Stop sync_gateway
- Deploy config
- Start sync_gateway
You would have to do these steps manually anyway to run the test or am I missing something?

**Comment by tleyden** [comment]
When I'm running locally, pointed to SG and CBS on my OSX dev workstation, any attempts to reset the cluster will fail anyway.  (this is for offline development where I don't have access to a VM cluster or an AWS cluster)

**Comment by sethrosetter** [comment]
@tleyden Can I close this now that we have vagrant?
