### ISSUE TITLE
1.2.1 sync_gateway Testing

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#365]
- [x] Run functional tests against 1.2.1(4;26c202a) + Couchbase Server 4.1.0
Results 96 / 98
- Known issue - functional_tests.test_users_channels.test_single_user_single_channel[CC-2] 
- SSH provisioning error - functional_tests/test_sync.py::test_sync_access_sanity[DI-1]
- reran locally, passed
- [x] Run Node.js tests  #http://qa.sc.couchbase.com/view/mobile/job/mac-sync-gateway-android-node-js-tests-cb/
   - [x] CBLite Android 1.1 with sync_gateway 1.2.1-4
   - [x] CBLite Android 1.2.0 with sync_gateway 1.2.1-4

**Comment by sethrosetter** [comment]
- [ ] CBLite Android 1.1 with sync_gateway 1.2.1-4

TEST FAILURES!!!
not ok tests/cbl-document.js .......................... 22/51

TEST FAILURES!!!
not ok tests/cbl-large-data.js .......................... 2/4

TEST FAILURES!!!
not ok tests/cbl-large-revisions-compact-revs-limit.js  65/67

1449/1482
TOTAL: 1482
PASSED: 1449
FAILED: 33

**Comment by sethrosetter** [comment]
### CBLite Android 1.2 with sync_gateway 1.2.1-4 using API 19 x86

http://qa.sc.couchbase.com/view/mobile/job/mac-sync-gateway-android-node-js-tests-cb/13/console

not ok tests/cbl-document.js .......................... 22/51

TEST FAILURES!!!
not ok tests/cbl-views.js ............................. 29/30

1422/1452
TOTAL: 1452
PASSED: 1422
FAILED: 30

**Comment by sethrosetter** [comment]
1** - Failed (Resolved in Android 1.2)

**Comment by tleyden** [comment]
- [ ] CBL views with LiteServAndroid 1.2.1 and SG 1.2.1
- [ ] CBLDocument with Android 1.1 or 1.2 with SG 1.2.0  (did they ever used to work?)

**Comment by tleyden** [comment]
According to @zgramana:

> Just confirmed the view test failure is a known java issue
