### ISSUE TITLE
Ability to override / disable version checking

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#453]
```
ValueError: Unexpected sync_gateway version!! Expected: b10f2fad7b4d435d8d2216c48bdc4f5f00ce26db Actual: ec46240
```

I manually built a different version of sync gateway on one of the machines, is there a way to disable the strict version checking?

**Comment by sethrosetter** [comment]
@tleyden Not at the moment. Are you trying to run different versions on different machines? Provision cluster should work as expected once this is fixed - https://github.com/couchbaselabs/mobile-testkit/issues/454

**Comment by tleyden** [comment]
I am, just because I only need to debug one machine.

**Comment by sethrosetter** [comment]
Closing this
