### ISSUE TITLE
ngrep capture misses changes feed 

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#468]
When sg-replicate runs, it will do a _changes feed request on *localhost*, which happens on the loopback iface, and so ngrep does not capture it since it only currently listens on eth0.

The `-d any` doesn't seem to work well, looks like the output gets interleaved and ends up as basically garbage.

Workaround: we could run three concurrent ngrep captures: `ngrep -d lo`, `ngrep -d eth0`, and `ngrep -d eth1`

**Comment by sethrosetter** [comment]
Off the top of my head, that seems like the best for now.

**Comment by tleyden** [comment]
PR: https://github.com/couchbaselabs/mobile-testkit/pull/470
