### ISSUE TITLE
Validate CLUSTER_CONFIG matches test

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#519]
If you have CLUSTER_CONFIG = 2sg_1cbs and run a test that expects 1sg_1cbs, things will fail b/c of mismatch.

Possible fix: validate CLUSTER_CONFIG in every test setup

Or maybe get rid of CLUSTER_CONFIG env variable and just always discover it.

Or instead of env variable, pass it in as `-v CLUSTER_CONFIG=` robot variable.  Safer, more intentional, removes env state.

**Comment by sethrosetter** [comment]
We have stripped environment variable usage when running tests in most places
