### ISSUE TITLE
Manual sync_gateway Open ID Connect Scenarios

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#538]
- [x] With backing server
- [x] Auth flow sanity checks 
  - [x] yahoo
  - [ ] paypal
  - [x] azure
- [ ] Implicit sanity checks using implicit flow _session (using Bearer header)
  - [ ] yahoo
  - [ ] paypal
  - [x] azure
- [ ] Server flow sample apps

**Comment by sethrosetter** [comment]
@adamcfraser Can this be closed?

**Comment by adamcfraser** [comment]
Validated auth code flow for Azure.  

Validated successful client instantiation for Paypal and Yahoo.  For Yahoo, the code provided after successful authentication was being rejected - appears to be an issue on the Yahoo side (potentially related to the test app being used.
