### ISSUE TITLE
Manually test OpenID Connect for Android

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#547]
- [x] Multiple API Levels for Android
    - [x] Android M/N
    - [x] Android API between 18 and 22,
    - [x] Android API 17 or lower.
- [ ] Test OIDC with yahoo (non default provider)

**Comment by pasin** [comment]
API 17 
- Google Auth Code Flow (PASS)
- Google Sign-in (Cannot find a working emulator with Google API to test)
- Clear Credential Tokens (PASS)

API 19
- Google Auth Code Flow (PASS)
- Google Sign-in (PASS)
- Clear Credential Tokens (PASS)

API 23
- Google Auth Code Flow (PASS)
- Google Sign-in (PASS)
- Clear Credential Tokens (PASS)

API 24
- Google Auth Code Flow (PASS)
- Google Sign-in (PASS)
- Clear Credential Tokens (PASS)

**Comment by pasin** [comment]
When testing with Yahoo Auth Code Flow. I got the following error in the log:

```
07-19 15:06:36.123 16533-16616/com.couchbase.grocerysync W/RemoteRequest: com.couchbase.lite.replicator.RemoteRequest {GET, http://us-west.testfest.couchbasemobile.com:4984/grocery-sync/_oidc_challenge?offline=true}: Got error status: 500 for http://us-west.testfest.couchbasemobile.com:4984/grocery-sync/_oidc_challenge?offline=true. Reason: Internal Server Error
```

**Comment by sethrosetter** [comment]
@pasin We are having issues with yahoo + Auth code flow, Do you mind trying the AzureAuthFlow + Auth code flow?

**Comment by sethrosetter** [comment]
I tested the platforms with azure.
