### ISSUE TITLE
Matplotlib not working

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#569]
Running into 

* http://stackoverflow.com/questions/33100969/matplotlib-example-code-not-working-on-python-virtual-environment
* http://stackoverflow.com/questions/35472693/how-to-get-matplotlib-pyplot-working-in-virtual-environment-on-osx

But actually, we should be pushing to a service (Greylog?)

**Comment by sethrosetter** [comment]
@tleyden I don't think this is still an issue due to using grafana / influx. Please reopen if you have an issue.
