### ISSUE TITLE
Functional test for - Handle invalid username characters in OIDC issuer, subject

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#574]
Sync Gateway bug: [Handle invalid username characters in OIDC issuer, subject](https://github.com/couchbase/sync_gateway/issues/1926)

**Comment by tleyden** [comment]
https://github.com/couchbase/sync_gateway/issues/1926

**Comment by adamcfraser** [comment]
There's a unit test for this - we should be fine without a functional test.
