### ISSUE TITLE
Nightly Android Matrix

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#598]
Create  #`_android-node-js-matrix` multiconfiguration job on UberJenkins - http://uberjenkins.sc.couchbase.com/

Matrix job parameters 
- LITESERV_ANDROID_VERSION

Defaults for downstream job
- Using API 23 x86 emulator
- Using macbuild as an agent
-  Trigger this job with the below matrix - http://uberjenkins.sc.couchbase.com/job/android-node-js-tests-walrus/

|| SG 1.3.0-274 + Client LITESERV_ANDROID_VERSION | SG 1.2.1-4 + Client LITESERV_ANDROID_VERSION | SG 1.1.1-10 + Client LITESERV_ANDROID_VERSION | 
|---|---|---|---|
|SQLite|
|SQLCipher|
|ForestDB|
|ForestDB+Encryption|

**Comment by andreibaranouski** [comment]
http://uberjenkins.sc.couchbase.com/view/All/job/_android-node-js-matrix/ done
