### ISSUE TITLE
Performance scenario: Read performance

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/mobile-testkit#608]
Sample use case:
```
 - 80 channels, 30K docs per channel, each doc is 1kb.  
 - Daily, the 30K docs get inserted per channel.  
 - 5000 clients each pull from one channel only, and are pulling all 30K docs.   
 - Want to measure how long it takes for all clients to pull the docs down.
```

Proposed perf test parameters:
 - docs/channel
 - users/channel
 - number of users
 - Sync Gateway config (to modify things like channel cache size)
 - Client changes parameters (limit in particular)

Test overview:
 - Pre-seed a DB with the docs (or write the docs at the start of the test, and don't start the perf evaluation until test completes)
 - Start all clients in parallel (another test that ramps up the number of clients as a stress test?)
 - Wait for all clients to get all docs
 - Determine an expected result based on test runs, add pass/fail based on comparison to that expected result?
 - monitor CPU/memory usage, ensure within a specified range

**Comment by tleyden** [comment]
Needs to know the channel names (cannot discover) -- will this be passed from the writer scenario?

**Comment by tleyden** [comment]
5000 clients each pull from one channel only, and are pulling all 30K docs.    <--- 5000 unique users

**Comment by tleyden** [comment]
* Changes feed with batchsize as the limit
* Bulk_get with batch size

**Comment by tleyden** [comment]
Writer params:

- **--numwriters** 100 writers This number doesn't need to be the same as `--numreaders`, but probably want > 1 for higher concurrent requests
- **--numdocs** 2.4 million total docs 
- **--numchannels** 80 channels 
- **--docsize** 1kb docsize

Reader params:

- **--numreaders** 5000 readers 
- **--chans-per-reader** 1 channel/reader

Steps:

1. Invoke writer scenario, get back
    - Channel names that were created
1. Invoke reader scenario
   - Figure out reader -> channel assignment
   - Spin up all reader goroutines.  Each reader:
       - Creates a reader user if needed with appropriate channel  (depending on --createreader flags) 
       - Pull all changes, passing in limit=batch_size
       - For each doc id that is pulled from changes feed batch, do a bulk_get to get doc contents
       - When no more changes available, goroutine ends

Issues:

1. Does `--createuser` need to get split into `--createwriter` and `--createreader`?  Ditto for `--usercreds` -> `--writercreds`?

**Comment by tleyden** [comment]
Close out criteria:

- [ ] Invoke writer in code

**Comment by tleyden** [comment]
Distribute channel assignment randomly among readers

```
INFO[09-20|14:25:38] Creating reader SG user                  username=readload-user-30-f2cadbc3-89cd-4a8d-8597-e40d6182f4a5 channels=[0-f2cadbc3-89cd-4a8d-8597-e40d6182f4a5]
INFO[09-20|14:25:38] Creating reader SG user                  username=readload-user-37-f2cadbc3-89cd-4a8d-8597-e40d6182f4a5 channels=[0-f2cadbc3-89cd-4a8d-8597-e40d6182f4a5]
INFO[09-20|14:25:38] Creating reader SG user                  username=readload-user-0-f2cadbc3-89cd-4a8d-8597-e40d6182f4a5 channels=[0-f2cadbc3-89cd-4a8d-8597-e40d6182f4a5]
INFO[09-20|14:25:38] Creating reader SG user                  username=readload-user-31-f2cadbc3-89cd-4a8d-8597-e40d6182f4a5 channels=[0-f2cadbc3-89cd-4a8d-8597-e40d6182f4a5]
INFO[09-20|14:25:38] Creating reader SG user                  username=readload-user-79-f2cadbc3-89cd-4a8d-8597-e40d6182f4a5 channels=[0-f2cadbc3-89cd-4a8d-8597-e40d6182f4a5]
INFO[09-20|14:25:38] Creating reader SG user                  username=readload-user-1-f2cadbc3-89cd-4a8d-8597-e40d6182f4a5 channels=[0-f2cadbc3-89cd-4a8d-8597-e40d6182f4a5]
```

**Comment by tleyden** [comment]
- [ ] Distribute channel assignment randomly among readers
- [ ] Add timing metric: start recording reader at top of of puller loop, stop recording after gotten all docs

**Comment by tleyden** [comment]
- [ ] Publish a counter of docs read / docs written -- can Grafana render as a rate to get docs / sec
