### ISSUE TITLE
Evaluate influx db for perf data management

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/mobile-testkit#615]
- [x] Set up Influx DB in existing mobile host (Seth to provide details on which machine that is)
 - [x] Test services start on reboot
 - [ ] Review Influx DB licensing
 - [x] Review creation of DBs per test run, 
 - [x] Look at expiry/cleanup of test results at some point (covered in #624)

**Comment by ajres** [comment]
Installed influxdb and grafana on host.

Used these [instructions](https://docs.influxdata.com/influxdb/v0.9/introduction/installation/) for influxdb
Used these [instructions](http://docs.grafana.org/installation/rpm/) for grafana 

Temporarily disable firewall as it is blocking ports for external access, need to configure then re-enable.

1) Port 3000 for accessing the grafana UI
2) Port 8086 for accessing the InfluxDB REST API

Local telegraf Agent has sent some data to remote influxDB

**Comment by ajres** [comment]
Tested changing the name of the influxdb database that telegraf writes to via the config file, this is working.

In grafana currently doing a manual update to the `Datasource` in the UI, need to see if this could be done via config.

**Comment by ajres** [comment]
firewall on vm updated, opened ports 3000 and 8086, used the following commands

`firewall-cmd --permanent --zone=public --add-port=3000/tcp`
`firewall-cmd --permanent --zone=public --add-port=8086/tcp`
`firewall-cmd reload`

**Comment by ajres** [comment]
Grafana supports scripted dashboards that are generated from a disk based .js file. This will allow us to generate a .js file for a particular test run and provide a link URL to the custom dashboard for that job (Link in Jenkins job?)

**Comment by ajres** [comment]
influxdb and grafana services started successfully after reboot

**Comment by adamcfraser** [comment]
No licensing concerns raised after review.
