### ISSUE TITLE
Create nightly macosx matrix

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#619]
Create  #`_macosx-node-js-matrix` multiconfiguration job on UberJenkins - http://uberjenkins.sc.couchbase.com/

Matrix job parameters 
- LITESERV_MACOSX_VERSION

Defaults for downstream job
- Using macbuild as an agent
-  Trigger this job with the below matrix - http://uberjenkins.sc.couchbase.com/job/macosx-liteserv-node-js-tests-walrus/

|| SG 1.3.0-274 + Client LITESERV_MACOSX_VERSION | SG 1.2.1-4 + Client LITESERV_MACOSX_VERSION | SG 1.1.1-10 + Client LITESERV_MACOSX_VERSION | 
|---|---|---|---|
|SQLite|
|SQLCipher|
|ForestDB|
|ForestDB+Encryption|

**Comment by andreibaranouski** [comment]
http://uberjenkins.sc.couchbase.com/job/_macosx-node-js-matrix/
