### ISSUE TITLE
Create functional test to simultaneously start multiple of the same replicators.

### ISSUE THREAD

**Issue by pasin** [couchbaselabs/mobile-testkit#632]
Steps:
1. Setup SGW with a database such as db
2. Create a local database such as db
3. Start 5 continuous push replicators with the exact same properties (e.g. same source and target) by using POST /_replicate
4. Make sure that the same session id returned from POST /_replicate.
5. Check the active tasks (GET /_active_tasks) and make sure there is only 1 task created.
6. Stop the replicator by POST /_replicate with cancel=true.
7. Repeat Step 3-6 by starting pull replicators instead.

**Comment by sethrosetter** [comment]
@pasin Should I do something similar for `continuous: false`?

**Comment by sethrosetter** [comment]
Also what is there a java-core reference issue?

**Comment by sethrosetter** [comment]
start large replication with concurrent oneshot POST _replicate with same parameters. There should only be one replicator running

**Comment by pasin** [comment]
This is the issue : https://github.com/couchbase/couchbase-lite-android/issues/939.

**Comment by sethrosetter** [comment]
After talking with @snej, the one shot replicate with concurrent requests do not seem like a useful test case due to the blocking nature of the one shot replication
