### ISSUE TITLE
Create functional test to start multiple replicators with different properties

### ISSUE THREAD

**Issue by pasin** [couchbaselabs/mobile-testkit#633]
1. Setup SGW with a remote database name db for an example
2. Create a local database such as db
3. Send POST /_replicate with source = db, target = <SGW DB>, continuous = true
4. Send POST /_replicate with source = db, target = <SGW DB>, continuous = true, doc_ids=["doc1", "doc2"]
5. Send POST /_replicate with source = db, target = <SGW DB>, continuous = true, filter="filter1"
6. Make sure that the session_id from each POST /_replicate are different.
7. Send GET /_active_tasks to make sure that there are 3 tasks created.
8. Send 3 POST /_replicate withe the same parameter as Step 3=5 plus cancel=true to stop those replicators
9. Repeat Step 3 - 8 with source = <SGW DB> and target = db for testing the pull replicator.

**Comment by pasin** [comment]
Reference issue: https://github.com/couchbase/couchbase-lite-java-core/issues/1386

**Comment by sethrosetter** [comment]
For push, LS -> SG, I used:
- continuous: true
- continuous: true, doc_ids=["doc1", "doc2"]
- continuous: true, filter="test/custom_filter"
For pull LS <- SG, I used:
- - continuous: true
- continuous: true, channels="NBC,CBS", filter="sync_gateway/bychannel"
