### ISSUE TITLE
Test CBL on IPv6-only network

### ISSUE THREAD

**Issue by snej** [couchbaselabs/mobile-testkit#637]
We should do some testing on IPv6-only networks, since Apple now requires that apps work in such environments (because wireless carriers are phasing out IPv4 on their cell networks.) Apple has so far rejected at least one CBL-using iOS app for failing.

[This video from WWDC 2015](https://developer.apple.com/videos/play/wwdc2015/719/?time=358
) shows an easy way to set up such a network by using Internet Sharing on a Mac. Then you can test devices that connect to that Mac as their WiFi base station.

**Comment by sethrosetter** [comment]
Need dedicated IPv6 router with own wireless network net.

**Comment by snej** [comment]
To match the behavior of cell networks, the router should support DNSv6 and NATv6 so that clients on its network can reach outside IPv4 servers.

**Comment by pasin** [comment]
I was able to successfully test ToDoLite iOS with Replication to the test fest server, BUT I couldn't test ToDoLite Android as the phone cannot connect to the Internet after connecting to the NAT64 WiFi setup on my Mac.

**Comment by sethrosetter** [comment]
@pasin and I were able to test TodoLite iOS 1.3.1-6 and Android 1.3.1-30 connected to a network exposed via my mac with Internet Sharing + NAT64 enabled. Both apps worked as expected. For 1.4, we should integrate some automated testing.
