### ISSUE TITLE
Automated end-to-end performance test

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/mobile-testkit#638]
- [x] Setup Jenkins job for end-to-end test.  Set of parameters would be superset of what's needed for locust, provisioning, etc.  Use a fixed hardware topology to run the tests on, but provisioning installs SG, CBS, etc.  Expects InfluxDB to already exist.
- [x] Datasource creation in Grafana
- [x] Name hosts to support filtering by host type in Grafana 
- [x] Provision telegraf agent on each host with appropriate configurations
- [x] Link in Jenkins output directly to Grafana dashboard for appropriate datasource
- [x] Telegraf agent lifecycle (when to start, ensuring shutdown)

**Comment by ajres** [comment]
After trying a number of Jenkins plugins, the only one, I could find, that will allow us to add a templated (i.e uses build params) URL link to a build page is [Rich Text Publisher Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Rich+Text+Publisher+Plugin)

**Comment by adamcfraser** [comment]
Need 
- [ ] PR to merge to testkit master
- [ ] Clean up the old perf jenkins job

**Comment by ajres** [comment]
The old perf test job has been disabled, I have left the job in place for now to provide access to the perf test results of old SG versions until we baseline off a new release with the new perf stats collection.

**Comment by tleyden** [comment]
- [ ] Remove code that polls gateload expvars and pushes to statsd / remove from telegraf repo
- [ ] Split grafana panels -- one panel works with sgload, but second panel for gateload

**Comment by tleyden** [comment]
Related to https://github.com/couchbaselabs/mobile-testkit/issues/209

**Comment by tleyden** [comment]
- [ ] Gateload pushtosubscriber stats are not showing up on Grafana
- [ ] Resubmit for PR review, assign to @sethrosetter

**Comment by sethrosetter** [comment]
@tleyden @ajres  Can this be closed?

**Comment by tleyden** [comment]
@sethrosetter I'm going to take a look at this
