### ISSUE TITLE
Investigate updating base AMI for cloudformation

### ISSUE THREAD

**Issue by jamiltz** [couchbaselabs/mobile-testkit#639]
This ImageId https://github.com/couchbaselabs/mobile-testkit/blob/master/libraries/provision/cloudformation_template.py#L132 is not available on the public market place.

Should we update to the latest CentOS 7 base image?

**Comment by sethrosetter** [comment]
@tleyden Do you have an opinion on this?

**Comment by tleyden** [comment]
Yes, we should bump this

**Comment by tleyden** [comment]
@jamiltz I just checked and that ami is still valid.  https://aws.amazon.com/marketplace/fulfillment?productId=b7ee8a69-ee97-4a49-9e68-afaee216db2e&ref_=dtl_psb_continue&region=us-east-1

<img width="727" alt="screen shot 2016-09-16 at 2 22 26 pm" src="https://cloud.githubusercontent.com/assets/296876/18601650/06b383d6-7c19-11e6-9d44-f7ddb12c41f9.png">

**Comment by jamiltz** [comment]
Yep! maybe I was looking in the wrong region.
