### ISSUE TITLE
Add Test Replication with Session cookie

### ISSUE THREAD

**Issue by pasin** [couchbaselabs/mobile-testkit#641]
I think it's a good idea to add this test to the functional tests as we don't have the unit test and the unit test cannot test this easily.

Setup:

1. SyncGateway Config with guest disabled = true and One user added (e.g. user1 / 1234).

Steps:

1. Create a new session on SGW for the user1 by using POST /_session. Capture the SyncGatewaySession cookie from the set-cookie in the response header.

2. Start continuous push and pull replicator on the LiteServ with SyncGatewaySession cookie. Make sure that both replicators start correctly.

 Sample POST /_replicate body:
 ```
// Push
{
      source: 'db',
      target: {
            url: 'http://10.17.2.133:4984/db',
            headers: {
                    Cookie: 'SyncGatewaySession=d92f44b908b5c9dd20b351fb4b8a6b273433387b; Path=/sync_gateway; Expires=Thu, 11 Aug 2016 17:53:49 GMT'
            } 
      },
      continuous: true
}
// Pull
{
      target: 'db',
      source: {
            url: 'http://10.17.2.133:4984/db',
            headers: {
                    Cookie: 'SyncGatewaySession=d92f44b908b5c9dd20b351fb4b8a6b273433387b; Path=/sync_gateway; Expires=Thu, 11 Aug 2016 17:53:49 GMT'
            } 
      },
      continuous: true
}
```
Note that I don't know if Path and Expires are required or not.

3. Delete the session from SGW by sending DELETE /_sessions/<sessionid> to SGW.

4. Cancel both push and pull replicator on the LiteServ.

5. Repeat step 1 and 2.

Reference: https://github.com/couchbase/couchbase-lite-android/issues/817.

**Comment by pasin** [comment]
From https://github.com/couchbase/couchbase-lite-android/issues/817#issuecomment-241710428, we should also include a test to check _active_tasks to detect the session deletion / expiration but this could be a bit tricky.

For Push replicator, we need to update/create a document to have the replicator recognizes. For Pull replicator, we need to wait until _changes feed timeout so the change tracker can resend the request and got 401 error.  Note that SGW has 5 mins default timeout.

**Comment by sethrosetter** [comment]
This should run with a backing couchbase server.
