### ISSUE TITLE
Integrate gateload w/ InfluxDB, Grafana

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/mobile-testkit#666]
Write a telegraf collector for the traditional gateload expvars, to support viewing standard gateload results via Grafana.

Would need to get incorporated into the mobile-testkit provisioning (similar to what's needed for SG perf testing).

**Comment by ajres** [comment]
https://github.com/couchbaselabs/telegraf/tree/master/plugins/inputs/gateload
