### ISSUE TITLE
Integration of sg_load w/ Jenkins perf jobs

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/mobile-testkit#670]
Integrate the new scenario runner into Jenkins, including:
- deployment/packaging
- input parameters to define what scenario is being run, parameters for that scenario

**Comment by tleyden** [comment]
Gated on https://github.com/couchbaselabs/mobile-testkit/issues/638

**Comment by ajres** [comment]
Initial integration of sgload with perf stats Jenkins job is pushed to per stats PR in SG repo.

**Comment by djpongh** [comment]
Work is done. Waiting for PR merge.

**Comment by sethrosetter** [comment]
@tleyden Can this be closed?
