### ISSUE TITLE
Extends sgload writer to include updates

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#675]

**Comment by adamcfraser** [comment]
Our write load generator needs the ability to generate updates, in addition to just inserts.

I think a useful input parameter to the write job to manage this would something that specifies the insert/update ratio (e.g. 50% inserts, 50% updates).  This might require some custom handling for the 100% update case (we need to write the initial doc somehow).

For an initial implementation, it's probably sufficient to distribute the updates evenly/randomly across the document set.  In future we might want to apply an update weighting, to be able to replicate scenarios where a few documents have many revisions, but most documents only have one or two.  That's not mandatory for the initial implementation.

**Comment by tleyden** [comment]
Writer:

Write 10 docs
Update each doc 100 times

Reader:

Should get 10 docs
Each rev id should be at 100-x

**Comment by tleyden** [comment]
Replicating gateload:

- Readers and Writers running concurrently
- Want a mix of inserts and updates
- Record failed to push / failed to pull
- Support graceful shutdown
   - Spin down writers
   - Block until all expected docs are run by readers

**Comment by tleyden** [comment]
* Phase 1: RT latency including inserts + updates, but no correctness .. user needs to kill it or specify total runtime
* Phase 2: Look into adding strict correctness verification that all writes were read (harder).  Might need graceful shutdown ability.

**Comment by tleyden** [comment]
Fixed in https://github.com/couchbaselabs/sgload/commit/7f745a84d3274ee739fac0edd199b0e85e4e9300 + earlier commits
