### ISSUE TITLE
Build Grafana dashboard panels for SG performance tests

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/mobile-testkit#677]
Design and implement dashboard panels for reviewing perf results.

**Comment by adamcfraser** [comment]
Define dashboard with the following panels:
 - [ ] Sync Gateway CPU (%)
 - [ ] Sync Gateway Memory usage (GB)
 - [ ] Gateload P95 
 - [ ] Gateload P99

For P95/P99, it would be useful to be able to see the average across all SG nodes, as well as being able to show the results as multiple lines on a single panel.

**Comment by ajres** [comment]
Do we want one particular category of P95/P99, if so which one?

**Comment by adamcfraser** [comment]
Updated the checklist above to indicate which P95/P99 to use.

**Comment by ajres** [comment]
Are P95/P99 units a simple counter, the values are in the 2-3Billion range.

**Comment by adamcfraser** [comment]
Time in nanoseconds.

**Comment by ajres** [comment]
{Latest dashboad](http://s61103cnt72.sc.couchbase.com:3000/dashboard/db/sync-gateway-perf-test)

**Comment by sethrosetter** [comment]
@ajres Can this be closed?
