### ISSUE TITLE
Add functional tests for sg_accel/DCP restart

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/mobile-testkit#688]
Add functional tests to specifically validate the following scenarios:
### DCP restart under load
1. Start sg_accel, sync_gateway
2. Start applying relatively high write load to sync_gateway
3. Stop sg_accel
4. Restart sg_accel
5. Stop writes, wait for indexing
6. Issue _changes request 

Pass criteria:
- no DCP rollbacks (can be found by parsing logs now, but may make sense to add diagnostics for this in sg_accel)
- all expected values are returned by _changes request

**Comment by sethrosetter** [comment]
Implement feature/strip-robot

**Comment by sethrosetter** [comment]
Take all sg_accel nodes down

**Comment by sethrosetter** [comment]
Spun into this ticket - https://github.com/couchbaselabs/mobile-testkit/issues/818
