### ISSUE TITLE
Testing for Sync Gateway log rotation

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/mobile-testkit#704]
We should include log rotation testing in our release checklist, to ensure we're not introducing any regressions.   This would need to cover the full range of OSes we support for Sync Gateway (with the possible exception/special handling for Windows).

Ideally we'd want a way to automate this, along with the other (currently manual) cross-platform installation testing.

**Comment by sethrosetter** [comment]
Tracking here - https://github.com/couchbaselabs/mobile-testkit/issues/778
