### ISSUE TITLE
sgload perf test Grafana should show roundtrip p95/p99 over the entire test run period

### ISSUE THREAD

**Issue by ajres** [couchbaselabs/mobile-testkit#751]
When running an sgload perf test, roundtrip p95/p99 is being generated by telegraf, it looks like this is being aggregated and reported for each sampling interval (10Seconds).

It would be more useful to calculate p95/p99 from the start of the test run to the current test time, in the same way as gateload currently does.

It's not clear if this can/should be resolved in statsd client, telegraf agent, grafana query builder.

Needs some investigation to find the best solution.

**Comment by ajres** [comment]
Updated graph with a moving_average(over the last ten samples), that shows a trend of the p95/p99 over time.

The values at the end of the test still don't represent the p95/p99 across the whole test run but rather the average over the last ten samples (dashboard default set to 5 minutes each sample) = 50minutes. The time interval for each sample can be changed on the graph panel in one place so the degree of averaging can be set as desired.

**Comment by ajres** [comment]
Please review and comment on whether this is usable for 1.4 perf testing or if further work is required.

**Comment by adamcfraser** [comment]
When viewing a live perf run, does this mean that the p95/99 only gets updated every 5 minutes?  Or is there a smaller sample window also being displayed, in addition to this one?

**Comment by ajres** [comment]
@adamcfraser good question, I have only used this on completed test runs, it does introduce a dead space at the front of the test which looks like it's average samples * time per sample. In the case above that's 50minutes. For end-of-run analysis this is less of an issue, but for live monitoring it would be necessary to modify the time interval on the graph panel to reduce the data buffer size.
