### ISSUE TITLE
Ability to run functional tests against load balancer

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#765]
- [x] include endpoint parameterization (either sg or lb)

**Comment by sethrosetter** [comment]
This will cover #1068

**Comment by tleyden** [comment]
There's already a test that runs against a load balancer, and there is provisioning code in place.

See: `topology specific / test_load_balancer`

**Comment by sethrosetter** [comment]
The ultimate goal is to be able to run all of our sync gateway tests with multiple sync gateways behind a load balancer.
