### ISSUE TITLE
Add LiteServ Java Support

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#771]
- [ ] Need build complete
- [ ] Implement support in test framework

**Comment by hideki** [comment]
@hideki's ToDos
- [ ] output filename change`couchase-lite-java-liteserv`
- [ ] version and build number are hard coded

**Comment by michaelkwok** [comment]
And currently will only support 1 type storage engine SQLite

**Comment by hideki** [comment]
@michaelkwok 
My part is done, can you build liteserv java on Jenkins?

**Comment by djpongh** [comment]
Created https://issues.couchbase.com/browse/MB-25537 to track
