### ISSUE TITLE
Add test case of P2P replication tests with attachment.

### ISSUE THREAD

**Issue by hideki** [couchbaselabs/mobile-testkit#777]
Original Ticket: https://github.com/couchbase/couchbase-lite-android/issues/1037

Test needs to cover variety of size of attachment. Small attachment could be embedded in JSON. Large one could be sent with Multi-part.

**Comment by sethrosetter** [comment]
Need these in P2p
- [ ] Push scenario
- [ ] Pull scenario

**Comment by sethrosetter** [comment]
Start with a basic cases in testsuites/listener/shared/client_client/
Start with macosx and net-mono

Push 
- Start a continuous push replication from client one -> client two on client one (example push - https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/listener/shared/client_client/test_peer_2_peer_sanity.py#L128-L133)
- Create doc with attachment on client one
- Verify the doc and attachment are sync'ed to client two

Pull
- Start a continuous push replication from client one <- client two on client one (example pull - https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/listener/shared/client_client/test_peer_2_peer_sanity.py#L135-L140)
- Create doc with attachment on client one
- Verify the doc and attachment are sync'ed to client two

**Comment by sethrosetter** [comment]
Attachments via HTTP -https://developer.couchbase.com/documentation/mobile/current/references/couchbase-lite/rest-api/index.html#!/document/put

testkit `create_doc` API - https://github.com/couchbaselabs/mobile-testkit/blob/master/keywords/document.py#L15-L47

testkit `add_doc` API - https://github.com/couchbaselabs/mobile-testkit/blob/master/keywords/MobileRestClient.py#L712-L745
