### ISSUE TITLE
Log rotation testing for sync gateway

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#778]
### Implementation Ticket
https://github.com/couchbase/sync_gateway/issues/2160

### Prerequisites
https://github.com/couchbaselabs/mobile-testkit/issues/779

### Behavior

- Max size (i.e. 10mb)

When the threshhold is meet, create a new log file (sg-log-2 or somthing similar), so we will have something similar to sg-log-1 (10mb), sg-log-2 (10mb), sg-log-3 (6mb, current log being written to)

- Max time (time to keep backups around, starts tracking on writing the backup). If the time is a day, all files older than a day should be removed.

- Max backups (number of backups to keep). If this is exceeded remove the oldest log.

### Questions
- What format do we support for times and sizes?
- What platforms are we required to test this on?
    - CentOS
    - Windows
- How to install SG on windows headless?

### Scenarios
- Check max size
   - successful creation of new log files

- Check max backups with default size
   - config type validation
   - successful deletion of log files backups

- Check max size + max backups
   - successful creation of new log files + successful deletion of log files backups

- (MANUAL) Check max time (in days, perhaps manual is the best for this)
   - successful deletion of log files backups

- (MANUAL) Check max time + max backups (in days, perhaps manual is the best for this)
   - successful deletion of log files backups

- (MANUAL) Check max size + max time + max backups (in days, perhaps manual is the best for this)
   - successful deletion of log files backups

**Comment by sethrosetter** [comment]
So to implement the non MANUAL tests, do the following,
- [  ] Create a new test module in the `testsuites/syncgateway/functional/tests` dir. Follow a test case such as https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/syncgateway/functional/tests/test_changes_backfill.py#L14-L23 for a sort of template
- [ ] Your test should include a configuration with logging enables and should be passed to the test case via a parameter. This will deploy the config provided to the test can make sure the cluster (SG + CB Server) are in a clean running state
- [ ] You may want to look into using this for validating log behavior - https://github.com/couchbaselabs/mobile-testkit/blob/master/keywords/RemoteExecutor.py

**Comment by sethrosetter** [comment]
For the manual max time, we may be able to mock the clock

**Comment by andreibaranouski** [comment]
https://github.com/couchbaselabs/mobile-testkit/pull/872

**Comment by sethrosetter** [comment]
@andreibaranouski Can you link any issues you have found here?

**Comment by andreibaranouski** [comment]
@sethrosetter can we close the ticket?

**Comment by sethrosetter** [comment]
@andreibaranouski Not yet. @raghusarangapani is currently testing on Windows.

**Comment by sethrosetter** [comment]
Also, I need to enhance these tests to support distributed index mode

**Comment by raghusarangapani** [comment]
The testing is done for log rotation on centos, windows, mac, ubuntu and RHEL. Will continue the log rotation windows feature support with the PR 918
