### ISSUE TITLE
Doc loader for Todo app for test fest

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#805]
- Add docs (tasks) in a loop for user1, user2 for a predefined lists

**Comment by jamiltz** [comment]
Here's a [load gen script](https://github.com/couchbaselabs/mobile-training-todo/blob/master/test/loadtest.js) that's using swagger spec.

Instructions (to remind myself to include in the readme):
- Run `npm install` in that directory to install the dependencies.
- It has [two scenarios](https://github.com/couchbaselabs/mobile-training-todo/blob/master/test/loadtest.js#L125-L135), you can write more and choose which scenario to run on [this line](https://github.com/couchbaselabs/mobile-training-todo/blob/master/test/loadtest.js#L103) and also update the SG URL [here](https://github.com/couchbaselabs/mobile-training-todo/blob/master/test/loadtest.js#L6).

It'd be good to repurpose the doc loader in the training under the performance testing lesson. We should talk about that in the offline on Monday.
