### ISSUE TITLE
Failing tests: Bucket shadowing + Distributed Indexing

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#811]
Test failing: 

```
pytest --skip-provisioning --pdb --mode=di -s --sync-gateway-version=1.4-12 --server-version=4.5.1 -k "test_bucket_shadow_low_revs_limit" testsuites/syncgateway/functional/topology_specific_tests/
```

I think it might be related to the fact that the tap feed is not started when distributed indexing is enabled, and so the push from SG -> source bucket never happens.

This code in database.go:

```
	// If not using channel index, start the tap feed
	if options.IndexOptions == nil {
		if err = context.tapListener.Start(bucket, options.TrackDocs, func(bucket string, err error) {
			context.TakeDbOffline("Lost TAP Feed")
		}); err != nil {
			return nil, err
		}
	}
```

**Comment by adamcfraser** [comment]
@tleyden Yep you're right - that IndexOptions check should also check whether there's a shadow bucket defined in the config.

**Comment by tleyden** [comment]
Blocked on https://github.com/couchbase/sync_gateway/issues/2193

**Comment by sethrosetter** [comment]
@tleyden Can we close this as it is tracked elsewhere?
