### ISSUE TITLE
Functional test to detect stale channel index bucket

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#813]
Steps to reproduce:
- Bring up single Sync Gateway node, backed by Couchbase Server.  
- Configure such that the primary bucket and the channel index bucket are different (which is the norm)
- Add several documents
- Shutdown Sync Gateway
- Flush the primary bucket, but **do not touch** the channel index bucket
- Start Sync Gateway
- Make sure that Sync Gateway starts without errors.

See https://github.com/couchbase/sync_gateway/issues/1133

**Comment by sethrosetter** [comment]
Expected behavior: Fail on startup

**Comment by sethrosetter** [comment]
Final test step (slightly different from above)
```
1. Bring up single Sync Gateway node, backed by Couchbase Server with 3 accels indexing
2. Configure such that the primary bucket and the channel index bucket are different (which is the norm)
3. Add 1000 documents
4. Shutdown Sync Gateway
5. Delete / create the primary bucket ('data-bucket'), but do not touch the channel index bucket
6. Start Sync Gateway
7. Assert that sync_gateway fails to start due to stale channel index
```
please verify @tleyden

**Comment by sethrosetter** [comment]
Functional test kicked off - http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/105/

**Comment by tleyden** [comment]
Unmerged PR: https://github.com/couchbaselabs/mobile-testkit/pull/839
