### ISSUE TITLE
Grafana no longer working

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#830]
On [this perf run](http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/198/) and previous perf runs, if I click the link to the [grafana dashboard](http://s61103cnt72.sc.couchbase.com:3000/dashboard/db/sync-gateway-perf-test?var-perftestrundbs=jenkins-sync-gateway-perf-test-198&from=1482258844885&to=1482266044886), I see this error:

![screen shot 2016-12-20 at 2 13 52 pm](https://cloud.githubusercontent.com/assets/296876/21370047/ba3fb61e-c6be-11e6-9401-599171bd2545.png)

**Comment by tleyden** [comment]
I ssh'd into the load generator running sgload via `ssh root@s61904cnt72.sc.couchbase.com`, and the telegraf logs look OK:

```
# tail -f /var/log/telegraf/telegraf.log
2016/12/20 15:36:40 Output [influxdb] buffer fullness: 24 / 10000 metrics. Total gathered metrics: 33913. Total dropped metrics: 0.
2016/12/20 15:36:40 Output [influxdb] wrote batch of 24 metrics in 7.016663ms
2016/12/20 15:36:50 Output [influxdb] buffer fullness: 24 / 10000 metrics. Total gathered metrics: 33937. Total dropped metrics: 0.
2016/12/20 15:36:50 Output [influxdb] wrote batch of 24 metrics in 2.710869ms
2016/12/20 15:37:00 Output [influxdb] buffer fullness: 24 / 10000 metrics. Total gathered metrics: 33961. Total dropped metrics: 0.
2016/12/20 15:37:00 Output [influxdb] wrote batch of 24 metrics in 4.80416ms
2016/12/20 15:37:10 Output [influxdb] buffer fullness: 24 / 10000 metrics. Total gathered metrics: 33985. Total dropped metrics: 0.
2016/12/20 15:37:10 Output [influxdb] wrote batch of 24 metrics in 4.959271ms
2016/12/20 15:37:20 Output [influxdb] buffer fullness: 24 / 10000 metrics. Total gathered metrics: 34009. Total dropped metrics: 0.
2016/12/20 15:37:20 Output [influxdb] wrote batch of 24 metrics in 3.168339ms
```

**Comment by tleyden** [comment]
I ssh'd into the machine where influx is running and ran `infux`:

```
> show databases
...
jenkins-sync-gateway-perf-test-198
...
```

and can see the db in question

**Comment by tleyden** [comment]
However, I don't see it in the list of grafana data sources:

![screen shot 2016-12-20 at 3 39 59 pm](https://cloud.githubusercontent.com/assets/296876/21372205/9f792318-c6ca-11e6-9f76-a6ee084a2a04.png)

so it seems like the code which creates the grafana source might be broken or not running.

is that [this code](https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/syncgateway/performance/run_sgload_perf_test.py#L118-L121)?

**Comment by ajres** [comment]
@tleyden 

I was suspicious that there are 100 data sources in the grafana currently.

This is the default limit as discussed [here](https://github.com/grafana/grafana/issues/3910)

Deleting unused data sources will fix this, but should this be a manual process so we can decide which ones to keep or a scheduled process that deletes the oldest runs?

**Comment by ajres** [comment]
The hosted InfluxDB / Grafana have been purged of old DB's and data sources. There is a new Jenkns job "perf-results-purge" this currently only handles the removal of "ALL" Grafana data sources that contain "perf" in their name. It could be extended to remove the associated influx-db as well.

**Comment by tleyden** [comment]
Ok great!
