### ISSUE TITLE
Ability to specify node type for hosts in pool.json file

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#831]
## Problem

The machine resource pool in the pool.json file looks like this:

```
{
   "ips":[
      "s61702cnt72.sc.couchbase.com",
      "s61703cnt72.sc.couchbase.com",
      "s61704cnt72.sc.couchbase.com",
      "s61705cnt72.sc.couchbase.com",
      "s61706cnt72.sc.couchbase.com",
      "s61901cnt72.sc.couchbase.com",
      "s61903cnt72.sc.couchbase.com",
      "s61904cnt72.sc.couchbase.com",
      "s61905cnt72.sc.couchbase.com"
   ]
}
```

and it is used to generate the "cluster config" files which look like this:

```

[pool]
ma1 ansible_host=ec2-54-89-189-134.compute-1.amazonaws.com
ma2 ansible_host=ec2-54-173-185-100.compute-1.amazonaws.com
ma3 ansible_host=ec2-54-89-180-148.compute-1.amazonaws.com
ma4 ansible_host=ec2-54-165-88-46.compute-1.amazonaws.com
...

[couchbase_servers]
cb1 ansible_host=ec2-54-92-213-75.compute-1.amazonaws.com
cb2 ansible_host=ec2-54-89-219-143.compute-1.amazonaws.com
cb3 ansible_host=ec2-54-89-180-148.compute-1.amazonaws.com

[sync_gateways]
sg1 ansible_host=ec2-54-92-213-71.compute-1.amazonaws.com

```

However, when you have a `pool.json` file, which might be [specified in a jenkins job](http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/build?delay=0sec) or [generated from an AWS cloudformation](https://github.com/couchbaselabs/mobile-testkit/blob/master/libraries/provision/generate_pools_json_from_aws.py) there is no way to say which resources in the `pool.json` will map to which node type (  couchbase_servers | sync_gateways | etc) in the resulting cluster config file. 

This is a problem if you want to have large sized VM's or EC2 instances dedicated for Couchbase Server, and much smaller VM's / EC2 instances for the Sync Gateway nodes.

## Proposed fix

Enhance the `pool.json` file to have type mapping/hinting:

```
{
   "ip_to_node_type": {
       "s61702cnt72.sc.couchbase.com": "couchbase_servers",
       "s61703cnt72.sc.couchbase.com": "couchbase_servers", 
       "s61704cnt72.sc.couchbase.com": "couchbase_servers",
       "s61705cnt72.sc.couchbase.com": "sync_gateways",
       ....
   } 
   "ips":[
      "s61702cnt72.sc.couchbase.com",
      "s61703cnt72.sc.couchbase.com",
      "s61704cnt72.sc.couchbase.com",
      "s61705cnt72.sc.couchbase.com",
      ....
   ]
}
```

and enhance the `generate_clusters_from_pool.py` script to look at the `ip_to_node_type` field, and if present, generate the cluster config files according to the mappings in the ip_to_node_type field.

If the `ip_to_node_type` field is not present, then `generate_clusters_from_pool.py` would just work in the same way it currently does.  

Also as part of this change, a unit test should be added for `generate_clusters_from_pool.py` which demonstrates that it works -- both with and without the `ip_to_node_type` field.

**Comment by sethrosetter** [comment]
make sure to test that the generation of ansible host config and .json config
