### ISSUE TITLE
Add Grafana dashboard for SG Accel

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#854]
I'm not seeing SG Accel on this dashboard:

![screen shot 2017-01-10 at 2 30 28 pm](https://cloud.githubusercontent.com/assets/296876/21827633/64e0ce04-d741-11e6-8e18-170a566e3dd1.png)

**Comment by tleyden** [comment]
This run has sg accel: http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/250/

**Comment by ajres** [comment]
@tleyden can this ticket be closed now?

**Comment by tleyden** [comment]
Yup
