### ISSUE TITLE
Collect go profiling

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#867]
We have a collection script https://github.com/couchbaselabs/mobile-testkit/blob/master/libraries/provision/ansible/playbooks/files/sync_gateway_collect_profile.py which is deployed via https://github.com/couchbaselabs/mobile-testkit/blob/master/libraries/provision/ansible/playbooks/start-gateload.yml#L28-L35

I think we just need to call at the end of the job - https://github.com/couchbaselabs/mobile-testkit/blob/master/libraries/utilities/fetch_sync_gateway_profile.py

**Comment by tleyden** [comment]
@adamcfraser run in progress: http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/286/

If that works, merge https://github.com/couchbaselabs/mobile-testkit/pull/869 to get to master

**Comment by tleyden** [comment]
If it's not on jenkins job, you can grab from the sync gateway or sg accel machine at /tmp/sync_gateway_profile.tar.gz
