### ISSUE TITLE
Write scenario in test fest with doc loader

### ISSUE THREAD

**Issue by jamiltz** [couchbaselabs/mobile-testkit#875]
Steps to repro:

1. Start SG with SGA (version 1.4-35 (DI))
2. Modify [users list](https://github.com/couchbaselabs/mobile-training-todo/blob/master/test/loadtest.js#L9) in doc load to match the ones in SG config
3. Start loader and run it until ~5000 docs are added (might need to change the [total time](https://github.com/couchbaselabs/mobile-training-todo/blob/master/test/loadtest.js#L78) it runs for)

_Observed:_
The total task count on each device (Android and/or iOS on 1.4) doesn't get updated after a while (completely stops). It's the same across each client which suggests it might be related to the clients not receiving notifications from the changes feed rather than replication speed. Once the doc loader is stopped, the total task count slowly increases over time to reach the expected total task count.

**Comment by sethrosetter** [comment]
This does not happen anymore with 1.4-98

**Comment by tleyden** [comment]
@sethrosetter seems like it would be a nice regression test to have in our functional test suite though .. and we could validate it against a pre-1.4-98 build

**Comment by sethrosetter** [comment]
I agree. I think a new ticket should be created. This was a tracking ticket to retest for strange test fest behavior.

**Comment by sethrosetter** [comment]
Implementation ticket - https://github.com/couchbaselabs/mobile-testkit/issues/984
