### ISSUE TITLE
Run basic gateload perf test with feedtype=longpoll

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/mobile-testkit#877]
We need to run a basic 2sg/2ac/2lg/3cbs 2500/2500 perf test using gateload against the latest code, but with gateload set to use longpoll instead of continuous.  

This will better exercise the hash value handling and last_seq handling.  We should review the results to:
 - compare P95/P99 results with an equivalent gateload/continuous 
 - verify correctness (docs pushed/pulled, failed to push/pull from gateload expvars)

**Comment by sethrosetter** [comment]
This is running. Blocked on - https://github.com/couchbaselabs/sync-gateway-accel/issues/52
