### ISSUE TITLE
Sanity test password bucket authentication

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#880]
while running DI with sgload

**Comment by adamcfraser** [comment]
Validated running sg and sg-accel against password secured buckets.  Works as expected when username and password are specified in the SG config. 

However, there is a usability issue that we should fix in 1.4.1 - the channel_index bucket requires the username field.  Ideally it would default username to bucketname, as is done for the data bucket.  

Filed https://github.com/couchbase/sync_gateway/issues/2341 to make that enhancement in future.
