### ISSUE TITLE
Manually test iOS backgrounding scenarios

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#939]
@raghusarangapani, please sync up with @snej with the scenarios that he would like to test

**Comment by raghusarangapani** [comment]
I spoke to Jens regarding the testing required. The main thing Jens wants us to test is app switching to and from background with encrypted filesystem.

A possible scenario:
- Launch an app and set it up to pull from a large DB.
- While it is replicating, press the power button to lock screen.
-> App loses access to its in memory files.
-> the CBL replicator should get an error.
- Wake up the device/unlock
-> If its a continuous replication, the app should resume replication. 
-> If its is not continuous, it won't resume replication.

NOTES: The filesystem security is an opt in feature, it can be opted in through xcode through a UI checkbox. Jens might have used grocerysync but he wasn't sure.

We can use James' doc loader to load docs for this scenario.

**Comment by sethrosetter** [comment]
@snej Do we have to use a specific version of iOS?

**Comment by sethrosetter** [comment]
We will test this as part of test fest today

**Comment by raghusarangapani** [comment]
Seth and Raghu tested the scenario with LiteServ 1.4-41, ios with SQLite and ForestDB+Encryption and load test tool. Things worked fine, no crashes or errors. Verified it with Jens and Pasin on the call
