### ISSUE TITLE
Sanity test log rotation on non automated platforms

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#940]
sg and sg_accel (with 1.4-X, latest RC)
- [x] Mac OSX
- [x] Ubuntu
- [x] RHEL 6.8

**Comment by raghusarangapani** [comment]
## Ubuntu 16.04:

Installed sync_gateway 1.4-103 and tested max size, maxbackup, maxage. Log rotation works fine.

## RHEL-6.6:

Installed sg_accel 1.4-103. Install works fine but the post install script sg_accel_service_install.sh errors out as below: 
`
ERROR: unknown OS "RedHatEnterpriseServer"
`
All files got installed under /opt/couchbase-sg-accel and sg_accel was not running.

I edited the sg_accel_service_install.sh  Line 233, to RedHat|CentOS|RedHatEnterpriseServer) snd got sg_accel working. There is no /etc/init.d/sg_accel file but “initctl stop/start sg_accel” works.

Tested max size, maxbackup, maxage. Log rotation works fine.
