### ISSUE TITLE
Investigate hanging test

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#950]
Run The same configuration as this job  - http://uberjenkins.sc.couchbase.com/job/listener-client-client/27/

The test (test_peer_2_peer_sanity) hung for 9 hours. I'm guessing it is a deadlock scenario. 

Please try to repro in a loop.

**Comment by raghusarangapani** [comment]
I am unable to reproduce this issue, Closing it after discussing it with Seth
