### ISSUE TITLE
Run Android Tests on Device

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#981]
Using sg build 1.4-102 and couchbase server 4.5.1
- [ ] MXA - 4.1.2 JellyBean, API 16 (Motorola Xoom Android 4.1.2 (API 16)
  - [ ] cc
  - [ ] di
- [ ] HN6P - 7.1 Nougat, API 25 (Huawei Nexus 6P, Raghu)
  - [ ] cc
  - [ ] di

**Comment by raghusarangapani** [comment]
All scenarios were completed on MXA/HN6P, cc/di, SQLite/SQLCipher, ALCSG/ACSGTS
